### ISSUE TITLE
QoL Improvement: Add an all-tracks SPC option

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#100]
I just had to run the installer to test a potential bug when the MSU and french translations were both patched to the v1.1 ROM (sadly, the french translation needs a v1.1 ROM), and while the bug turned out to be a patching problem on the user's end (still don't know what he did wrong, but got him taken care of already), the longest part of the process was going through and selecting SPC for each individual track, as I didn't need to download any music for the test.

So I suggest, as a QoL improvement, to add an "All SPC" option to the patcher, so in cases someone wants to apply the patch without downloading any of the music they can do it with 1 click, rather than 100.

**Comment by Dizzy611** [comment]
We've discussed this on Discord but just making a note here that I agree and will be implementing this in the next version of the Installer, alongside other improvements I've been wanting to make.

**Comment by Dizzy611** [comment]
This is now part of the new installer.
