### ISSUE TITLE
Ted Woolsey Uncensored Edition just updated to 3.0

### ISSUE THREAD

**Issue by GregariousJB** [Insidious611/DancingMadFF6#101]
https://www.romhacking.net/forum/index.php?topic=32196.0

Just found this interesting project and I thought I'd let you know. Thank you.

**Comment by Dizzy611** [comment]
Thank you for the update! I haven't been paying close enough attention to TWUE. 

Not that it usually does, but here's hoping 3.0 doesn't cause any new issues for Dancing Mad.

**Comment by Dizzy611** [comment]
(I should be able to hotfix this without changing the installer much if at all, so expect this one fixed fairly soon)

**Comment by Dizzy611** [comment]
Updated the ipses on our servers to match. Would appreciate some testing to make sure the new version of TWUE hasn't caused compatibility issues, though it usually doesn't.

If you experience any bugs with TWUE 3.0 as installed using our installer, please open a new issue.
