### ISSUE TITLE
Server Issue: bigfuckin.rocks server only working server.

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#103]
All the servers in the current mirrors.dat file are down except for: https://bigfuckin.rocks/ff6data/
Yes, that includes the Cloudfront server.

**Comment by Dizzy611** [comment]
I'm not having any issues accessing Cloudfront myself. https://d9z02nz0xcifk.cloudfront.net/OST/ff3-1.pcm gives me an immediate download option. Can you let me know exactly the error you're getting?

Will fix shodan.dev to reflect its new URL, though.

**Comment by Dizzy611** [comment]
Leaving this issue open to remind myself to finish the changes to downloadpage.py that grab mirrors.dat from github instead of using the local copy when possible.

mirrors.dat itself has been fixed, and new installers uploaded.

**Comment by Dizzy611** [comment]
Closing this as the mirrors.dat/songs.xml downloading has been moved to part of the roadmap for the new installer, which is noted on the Discord.
