### ISSUE TITLE
Resume issue on sd2snes cart

### ISSUE THREAD

**Issue by ratix98** [Insidious611/DancingMadFF6#104]
After every battle I fight the music starts over again from the beginning. Cartridge used is an sd2snes cart Revision F utilizing the lastest firmware.  firmware version 1.11.0b1. 
Rom images used are US V1.0 & V1.1. Both versions will not resume while playing on the snes.
no other patches were used other then the options given in the installer.

selections used in the installer
sd2snes/snes9x-msu
developers recommendation

**Comment by Dizzy611** [comment]
I'm not sure Rev. F hardware is capable of resume, that's fairly old at this point and resume support was only added to the SD2SNES in 2017.

**Comment by ratix98** [comment]
Resume is indeed working on revision F and can be seen here https://www.youtube.com/watch?v=HwfttENMY0E&t=41s
and just to be absolutely sure about resume on the cart I used a different card and patched from scratch a vanilla Chrono Trigger image and reloaded.

**Comment by Dizzy611** [comment]
Interesting. Okay, so if it's working with other games it's probably something to do with my code checking for the MSU revision to enable resume then. 

I'm very busy at the moment so it's going to take me a while to get around to building the patch, but if you're willing to help me test this, I can give you an IPS that skips all MSU revision checking and just assumes all MSU hardware has resume support, so that we can at least potentially eliminate that as a reason

**Comment by ratix98** [comment]
Alright, I am willing to test. Take all the time needed.

**Comment by Dizzy611** [comment]
I now have an FX Pak Pro myself and am encountering the same issue on 1.11.0b1 but not 1.10.3. Chasing this up with ikari.

**Comment by Dizzy611** [comment]
@ratix98 Please try this IPS: https://github.com/Dizzy611/DancingMadFF6/blob/resume-support-workaround/patch/ff3msu.ips?raw=true

It appears to fix (well, more work around) the issue for me, allowing resume to work on 1.11.0b1

Please note that behavior on old MSU-1 implementations without resume is unknown.

Apply the IPS to an unmodified FF3 ROM, if applying TWUE or the music player, apply these after (I have confirmed these still work, myself)

**Comment by ratix98** [comment]
@Dizzy611 Yes, this work around works on the US version 1.0 of the game on the sd2snes with 1.11.0b1. 
Thank you

**Comment by Dizzy611** [comment]
This workaround has now been made permanent for the moment.
