### ISSUE TITLE
ChrystalChameleon tracks batch 2

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#115]
https://mega.nz/file/WZhAGKwI#bc_s694GHhO9qKOGGEWyk8t8Ky3N5WoPHl147xbZ_HY

8 new tracks, all converted and looped and ready to go... Though Celes' Theme's loop point is kinda bad...

**Comment by Dizzy611** [comment]
Wasn't intending to close this, 1583e45 was only a partial fix.

**Comment by Dizzy611** [comment]
Alright, this is basically fixed now as of 2a5a65e, just need to push out a new installer.

**Comment by edale2** [comment]
ChrystalChameleon's Under Martial Law, just released a few days ago.
https://www.youtube.com/watch?v=sutD--NhYdE

[ff3-29.zip](https://github.com/Dizzy611/DancingMadFF6/files/9998559/ff3-29.zip)
https://mega.nz/file/DYQ3mZSb#xhr7g7ZgcnHfnbhY-y8jBSsz_fNuGbI-3GrYrFJf_SI

**Comment by edale2** [comment]
Gau's Theme.
https://www.youtube.com/watch?v=lOsYrL1wy0A

https://mega.nz/file/yVZmRJTQ#zmS8gFHtWagWol3zpKzNMVMS7hx-wcHsATM8FqVu_qY

**Comment by edale2** [comment]
Shadow's Theme.
https://www.youtube.com/watch?v=SmRmnE2_fnY

https://mega.nz/file/SY4z1LAS#YGnvOw5dbSVctSuxF1uG73M2AZ--8ia8Y-GOVHj89zo

**Comment by edale2** [comment]
Decisive Battle.
https://www.youtube.com/watch?v=-FFtdlQ_5LU
https://mega.nz/file/zdZ3mRaa#TY3Oc_YXSg6YiFMoQsOAH1C0kGGSPqqakCQsZF8dMyM

**Comment by edale2** [comment]
Metamorphosis:
https://www.youtube.com/watch?v=Bk7eCqcEIls&pp=wgIGCgQQAhgB
https://mega.nz/file/CEZV3bwQ#JyvaNensJV5sXQnJ7G9bdj1syVfsNMA099ISXYKPGyM

**Comment by Dizzy611** [comment]
As mentioned on Discord (posting this mostly so others can see) I'm waiting for a while to see if more tracks are released before batching these together.

**Comment by edale2** [comment]
Kids Run Through the City Corner:
https://www.youtube.com/watch?v=HomTK7JzRT0
https://mega.nz/file/vdRWgSYQ#2GKEZWVSf8GUU1SN52HLEPofXQxIZ2VRfL03lZQCISc

**Comment by edale2** [comment]
Locke's Theme:
https://www.youtube.com/watch?v=EPlbbFvtC08
https://mega.nz/file/CJgHiLDS#Q5kVavy4n3ddO84jCUqI-axTRO7LFoN4sBegZ_EaYBY

**Comment by edale2** [comment]
Mt. Koltz
https://www.youtube.com/watch?v=Jg_u1lyaNe0
https://mega.nz/file/fEQG1ApB#1FemD1BRAJ9AofpoLZnfNaq9_wwdWdwtPm2Sqql4kAg

**Comment by edale2** [comment]
Techno de Chocobo:
https://www.youtube.com/watch?v=QZFHeJGD9PI
https://mega.nz/file/DRoUAa5A#sBtwN_He0evGcNjPjPoqASjtmtWeYmfE3uvdYRzEq1Q

**Comment by edale2** [comment]
Gogo's Theme:
https://www.youtube.com/watch?v=BZUkdc_-76c
https://mega.nz/file/7EgV2AhS#LWvCpjYTKJ048Df8XNI_BmVj2AHG4pThCx1-pANiNpI

**Comment by edale2** [comment]
Ghestal Empire:
https://www.youtube.com/watch?v=veAFgWJ-wBs
https://mega.nz/file/iFIhTKwD#_PySi-2aIeywjL1YAWCMQji4yKyK9VSrfu6zknKdLRk

**Comment by edale2** [comment]
Relm:
https://www.youtube.com/watch?v=VfWnknkW2iI
https://mega.nz/file/ncogjDIb#VY8pZmzrWsZAK2MwpOdkUVXeDXrRotWBRXHzXV5fDWc

**Comment by edale2** [comment]
Mog's Theme:
https://www.youtube.com/watch?v=SQb4Tjp_UMI
https://mega.nz/file/KFommCDJ#QMIidRWHOncGTbUL3UujlPGbVEb8pibQl0D-vAexRnQ

**Comment by edale2** [comment]
Catastrophe:
https://www.youtube.com/watch?v=NK7wCNDWloo
https://mega.nz/file/SBATjSLb#625cRVunaNIHdtSbMciBSVJJ7aFu-QY7OoSf9NnKQlg

**Comment by edale2** [comment]
The Airship Blackjack:
https://www.youtube.com/watch?v=hH1f4nfvwXA
https://mega.nz/file/zMBGXTqJ#Ec--e_9v455JtCL_w216LNO5tJg8EFqPBIiUCqNva7s

**Comment by edale2** [comment]
Floating Continent:
https://www.youtube.com/watch?v=L_rrh087RKk
https://mega.nz/file/LZxERTaL#3BOgSPGFisQIU0JL0aSBc0P70J87CC7v8XQdQOTjx68

**Comment by edale2** [comment]
Prelude:
https://www.youtube.com/watch?v=bIP6toZXgFk
https://mega.nz/file/SYoxhSqS#a4YSugxalfmhj6ESF2n265D7ehP9aDAqQ0-ijHu3-vw

**Comment by Dizzy611** [comment]
All tracks are now part of the new installer.
