### ISSUE TITLE
Installer cannot download file

### ISSUE THREAD

**Issue by robvangeloven** [Insidious611/DancingMadFF6#116]
Installer fails with cUrl error downloading / checksumming file 34/81

**Comment by Dizzy611** [comment]
There should be a log (called dancing-mad-installer.log) in your Users directory (or /home/username on linux). If you could attach it for me I'd appreciate it.

It's useful primarily for letting me know which mirror you're having issues with. It's likely the Amazon mirror, one day the permissions just kind of broke.

**Comment by Dizzy611** [comment]
Since you haven't commented with the log I need since posting the bug, I'm going to close this under the assumption this was a temporary mirror issue you've been unable to reproduce. Feel free to reopen when you have the log I need.
