### ISSUE TITLE
Please add support for "Random Encounters Menu Option" romhack

### ISSUE THREAD

**Issue by MoTem** [Insidious611/DancingMadFF6#121]
The romhack adds a simple menu option to disable or adjust random encounter rate. 

https://www.romhacking.net/hacks/6535/

I will add that its fully compatible with the latest Ted Woosley patch (3.06) according to my testing. I used the simple on/off variant.

**Comment by edale2** [comment]
Have you actually tried applying it, and found there to be compatibility issues?
