### ISSUE TITLE
Redid OCR 76, it's better now (hopefully)

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#13]
OK, so like I said, now that I'm done going through all the music selections, I'm planning on trying to convert The Black Mages' version of The Decisive Battle to MSU-1 format.

Because that's going to be a rather annoying song to find a good loop point for, I decided to do a quick easy project first while learning the process.

OCR track 76 is far superior to OST track 76 in my humble opinion, but there was one thing about it I didn't like at all.

This is OCR track 76 as it currently stands:
![ost 76 orig](https://user-images.githubusercontent.com/20962345/31262941-c5c54e66-aa2c-11e7-835b-8c75bf389326.png)

What I did was this:
![ost 76 edited](https://user-images.githubusercontent.com/20962345/31262964-f4c10188-aa2c-11e7-8c2d-f41b14cb8a9b.png)

I cut out the first half of the intro, as it did nothing to add to the track. Not to mention the pauses in music isn't something you want in an overworld theme song as can be seen from the original track, which jumps straight into the music, and stays there:
![screenshot - 10_6_2017 12_28_56 am](https://user-images.githubusercontent.com/20962345/31263033-68e5e07e-aa2d-11e7-9e55-2caff86ab57d.png)

 The bit at the end wasn't in the original file, was added for looping purposes by the first guy that worked on this. There apparently is no end-point set for loops, just a start point, and it loops at the end of the track (at least with the program I used), so rather than looping to the middle of a very busy section, I cut off the very end, and looped to the start of that section (right around the 40 second mark, the very noticeable spike).

The file _should_ be completely done and ready, I just need to test the looping somehow (given it's a WoR song, getting there in-game is right out).

https://mega.nz/#!eUpwgJyB!mmLfg8wau8GB7WgwHlwT_QoV6UjtCFsrBIbnyO-Wl2I

*edit- Figured out a simple way to test the looping, renamed to ff3-1.pcm, and just sat on the load screen to listen to the track. Normal was fine, but had put the wrong loop point in when converting the deamplified one, fixed, mega link updated with the new file.

First foray into MSU-1 audio file making... Success!

**Comment by Dizzy611** [comment]
A definite improvement! Thank you very much. I've dropped this into my local working folder along with the fixed OTH-34 from issue #12.

**Comment by qwertymodo** [comment]
If you want an easy way to test your loops, I wrote a foobar2k plugin to load MSU-1 .pcm files.  The only caveat is that if the loop point is set to 0, it won't loop (done intentionally so it wouldn't endlessly loop short jingles and things like that which aren't supposed to loop). However, if you do have a file which is SUPPOSED to loop back to sample 0, there's an easy solution there, just use the normal track repeat function.  https://github.com/qwertymodo/foo_input_msu/releases

**Comment by edale2** [comment]
Nice. Didn't have foobar before, but do now, and it plays and loops PCM audio great with your .dll installed.

Definitely quicker than putting it in a game and listening through the whole track.

@Insidious611 This is the type of thing that makes me call Qwertymodo one of the leading authorities on MSU-1 mods,.
