### ISSUE TITLE
One more new track for you.

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#15]
This time it's The Black Mages' version of "Battle."

Try as I might, I couldn't find any usable loop points, so this one's the whole song looping back on itself. 

It's still epic.

This is another one like OCR's where it could easily be used for a boss fight, but at the same time, it can still work as the basic battle theme, That said I'm sticking with the FFT version for my personal setup. Did it because "why not?".

https://mega.nz/#!uYpGTDrC!l4HBp6HzGT9dI6LBV3uYgmDqOBKDoS7EVpWNaue8vnw

Both versions again, but tested this (and Decisive Battle) in an actual fight in-game, and the deamp (or deamp v2 in Decisive Battle case) is balanced decently with the in-game sound effects. I think that's a test I'm gonna wanna run with all the tracks I'm using (add another few days of work on my end, damn my OCD, lol).

If you can get me any info I'll need to try converting Dancing Mad, I'll try and convert TBM's version of Dancing Mad as well (truly epic 12 minute rendition).

Oh, and if you have any tracks you want turned into PCM audio for this, I'll be happy to give it a shot.

**Comment by Dizzy611** [comment]
Accepted, tested, and staged for later upload.

**Comment by Dizzy611** [comment]
Yeah I'm also sticking with my previous selection for this one, it's a good track but it builds a bit too slowly. Not in a bad way musically but you can't really enjoy it when using it ingame, most normal fights don't last long enough.

Always good to have options though, that was the whole point of setting this up the way I did :p

**Comment by edale2** [comment]
Yea, like I said, I mostly did this one because I did the other TBM FFVI covers (except their cover of the opera).
