### ISSUE TITLE
An enhanced version of SSC track 32 this time

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#16]
So when I was going over the tracks. one thing I really liked about some of them was the inclusion of ambient sound.

This won FFT-2 it's spot on my picks for it's great use of the thunder effects to match the title screen's lightning. It also got OST-79 my vote, because nothing gets the total desolation of the abandoned WoR Narshe like the sounds of the howling wind, really helps it to pack an emotional punch.

So when I was going over track 32 (Phantom Train), I loved the train effects in FFT's and OCR's tracks, but OCR's was _horribly_ wrong genre, and FFT's was mastered atrociously (has a near-constant buzzing sound I couldn't eliminate). So I ended up settling for SSC's version.

But I got to thinking... Why not add the ambient train sound effects in myself? And why limit it to only the intro? you're on a train the whole time the song's playing after all.

So I did some looking around, and the best train effects I could find that didn't include things like the whistle blowing, just it moving over the tracks, was only 40 seconds long, lol.

I found a decent 5-6 second chunk of it that could loop with no problems, and copy, pasted it over and over to fill the timeline, lol. Had to do a -30dB deamplification on the train sounds to get them to not overwhelm the music, but the end result;

https://mega.nz/#!mAYh3BBJ!HAe6RxYNP-FWsd9Tncz3fYaU4_VzKZnSTRqpKx1SCco

A copy of SSC's version of Phantom Train, with some nice ambient train sounds that really match up well with the idea of riding on a train for that part of the game.

I'm not sure if you'd classify this one as SSC or OTH (kinda did this one mostly for myself), but here you go anyways. I'm definitely using this version for my setup.

**Comment by Dizzy611** [comment]
Excellent work! It definitely adds a lot to the ambience, I had to play to the phantom train so I could test it :P and it worked well. I think we'll put that in OTH since it's definitely a significant edit. 

Accepted and staged for upload.

**Comment by edale2** [comment]
Gimme a copy of you pre-phantom train .srm pls, I wanna try it out in it's natural environment too! :)

**Comment by edale2** [comment]
Eh, played through to the train myself (once I figured out which save to grab it was only like 10 minutes to get there). It's as good as I hoped. :)
