### ISSUE TITLE
Dancing Mad, The Black Mages Edition

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#18]
OK, I've finally finished with TBM's version of Dancing Mad.
https://mega.nz/#F!uZIT3Z4A!LJJlhcRL7MLllZpoHwowHw

Got the flac files for all 3 TBM tracks, a zip with the 4 tracks, and a track 82 v2 on there. Only the normal tracks, since you have that nifty new script to normalize them.

When I started, I got the first section isolated, and it was ridiculously easy to find a good loop point. I started to think converting it would be easy at that point... I should have known better than to think that.

Parts 2 and 3 just did not want to have a loop point, and you don't want to know how long it took me to figure out where to end track 2, actually had 1/2 of track 3 in there at first.

Part 4... I made some adjustments to.

Firstly, TBM cover of Dancing Mad doesn't have an equivalent to the chords that play as the final form of Kefka lowers, and not having that really affected the dramatic tone, so I copied that chunk from the OST and added it in (took 3 test runs to get the timing of the chords to match the action on screen).

It also lacked something very integral to Kefka's character, Kefka's laugh that plays at the end of the loop. I went and added that in as well.

The ff3-82 v2 PCM is because I noticed one of the laughs I had added into the start of the song timed almost perfectly with a SPC call of that sound, to the point they overlapped. I took that one out.

Only the normal tracks, since you have that nifty new script to normalize them.

Final analysis:
Track 101: perfect
Track 102: not happy, couldn't use all the decent loop point I thought I found because of changes in background instruments. Not sure I can do better than this. Also, a bit short.
Track 103: Similar to track 102, but a bit of a better looping job.
Track 82: Epic. not the best, but passable, loop, but this part is 6 minutes long, so that shouldn't be an issue.

**Comment by Dizzy611** [comment]
Covarr had a lot of trouble with dancing mad OCR and I expect it was for the same reasons. He also did some extensive edits to get it to work iirc.

**Comment by edale2** [comment]
I didn't really *need* to do those edits I did, and neither of them affected the looping

Both were done more to preserve some of the parts of that bit of the song that made it so memorable to begin with. FFVI was amazingly good at using the music to increase the dramatic tension and emotional involvement, and I wanted to preserve as much of that as I could for Dancing Mad and amazing guitar riffs only get you so far. ;)

*edit- lol, I was just going over the 3 copies of Wild West to pick which one I wanted to use. I recognized something about SSC's one right away. With the shift in the type of drum used in the OST to the type used in SSC the 4-beat drum pattern that is constant throughout the song is the EXACT same one that plays in the prehistoric world (65,000,000 BC I think it was) in Chrono Trigger. The other instrumental parts are different, but the drum is the most prominent part of both of them.

**Comment by Dizzy611** [comment]
Uploading these to the server now. 

Added to installer's "sources" file as well.

**Comment by Dizzy611** [comment]
Upload done. Closing issue. Thanks!

**Comment by Dizzy611** [comment]
So I've been testing with these and I like them. The looping isn't perfect as you said but it's not bad. Dunno if I prefer these or the OCR versions, it's a really tough call.

**Comment by edale2** [comment]
My main problem with the OCR tracks of Dancing Mad? It doesn't sound like Dancing Mad.

All the other OCR tracks you can definitely hear the original track's influence in the music, Dancing Mad sound like a completely new song.
