### ISSUE TITLE
Track 39 (hex 0x27), Aria de Mezzo Carattare issues.

### ISSUE THREAD

**Issue by Dizzy611** [Insidious611/DancingMadFF6#21]
Continuing on from the (otherwise mostly fixed) Opera issues, here are the remaining problems.

A. Track is too long, the intro takes forever to play out leaving Celes silent until she's almost all the way through her part textwise. (PCM edits needed)

B. Interactivity of scene will desync even a perfectly edited PCM (Extensive ASM/scene code rewriting needed, I'd consider this a 'post release' problem)

**Comment by edale2** [comment]
I can try my hand at the PCM edits, but I'd need the PCM to edit.

The only version of this on your server atm is the OTH one.

**Comment by Dizzy611** [comment]
Thats the exact one that has issues. I grabbed it and renamed it for
testing.

**Comment by Dizzy611** [comment]
In fact, if you check the "new" folder you'll notice it's no longer listed as disabled. :P

That's the already normalized version though, if you're doing edits I'd take the full-amplitude version from http://www.somebodyelsesproblem.org/ff6data/OTH/ff3-39-disabled.pcm

The opera is so hard to time and loop at all that the OTH and OCR versions were the only ones we ever did, and then we had to can the OCR versions because they're just too slow. So there's only one source for the opera.

**Comment by edale2** [comment]
The current IPS has the opera fix?

**Comment by edale2** [comment]
Youch, 17 minutes... and this one *wasn't* too long? Do you know how long the original SPC audio track was?

**Comment by Dizzy611** [comment]
That's part of the problem, with this specific track the answer is
basically "as long as it takes you to finish this section of the game".

That said, if you get to that bit in the opera (it's the part where you
have to choose the right words with celes) and it plays the PCM you'll see
the timing problem immediately, as unlike all the other vocals that are
timed right hers are silent up until the third verse.

**Comment by Dizzy611** [comment]
Basically, there's no easy answer, figuring this out is going to take
playtesting.

And yes, the current ips patch in the patch folder should have the opera
fixed.

**Comment by edale2** [comment]
I'll consider it a win if the timing matches up decently to someone giving the right answer in a quick fashion (not staying  on the choice screen for a minute or two)

**Comment by Dizzy611** [comment]
Yeah, that's what I'd aim for as well

Just to be clear, https://github.com/Insidious611/DancingMadFF6/blob/master/patch/ff3msu.ips is what you should be using. The ips under the installer directory hasn't been updated to match. Well, it has, but only on my local copy as I'm doing a lot of installer testing atm.

**Comment by edale2** [comment]
Hmmm... seems a good chunk of this is for different parts of the Opera, rather than the aria, this might be able to be cut down to a 6ish minute track.

**Comment by edale2** [comment]
Yea, what's definitely "Grand Finale" starts at around the 11 minute mark, definitely has other parts of the Opera.

**Comment by edale2** [comment]
Hmmm... I didn't even notice the experimental branch before, I've just been using the Master branch.

Both Master and Experimental branches show they got an IPS update 8ish hours ago.

*edit- Oh, lol, misread, yea, the ips in the install directory hasn't been updated in a year, it looks like.

**Comment by edale2** [comment]
Well... I go looking for the OST, so I can check that version, and not only find it, but also ALL the SPC audio for FFVI (and almost every other SNES game). Was a challenge finding a player that would work in a x64 environment, but finally found SNESamp (plugin for WinAmp) on `https://www.zophar.net/utilities/spc.html` that actually works. Original song for Aria is only 3:50 long (and only 66kb!? damn good compression), lol.

**Comment by edale2** [comment]
And the OST is 3:53... the timing should already match up perfectly....  (IIRC the track starts over if you mess up and have to try again, so it doesn't actually loop, I'll have to playtest that to be sure though)

What was the problem with the OST again? maybe it was one of the other Opera tracks that gave problems... 

I've yet to try anything in-game, but if the timing is for a 3:50 ish track, I probably won't be able to do much with the 6ish minute OTH track. (not saying I won't try, just that I don't expect success).

**Comment by Dizzy611** [comment]
Well, the problem there is that the OST version either wouldn't have the singing at all, or it would be off as well and the issue there is that even with the better fidelity of the tracks, due to the timing problems it's going to sound worse than just turning the MSU-1 off for that bit. 

So for people who want the OST sound I'd rather just offer them the original opera, because the special effects the game uses for that segment, the same ones I had to workaround to get it working, won't really work with an MSU-1 version of the sound track.

As far as the OST opera in general and editing reasons it didn't work, I'm pretty sure that's actually down to other tracks (amusingly enough, in the non-interactive sections) that get swapped in and out very quickly in such a way that editing them based on what is essentially a CD recording of a sound chip capable of mixing music in a way the MSU-1 can't, just wasn't possible while delivering something of comparable quality. A big one here is... I forget the track number now, but in the previous Opera issue when I was testing to see what worked before the fix, I listed it as "Draco's speech". It's a seperate track that plays just for him singing, and in the original it actually plays on top of a backing track, which is a continuation of the track that plays directly before it, and which continues to play after that track is done. Switching back and forth works okay with the OTH versions but with the OST you'd immediately notice something was wrong because I can't guarantee split second track switches. 

The reason we have the OTH tracks in the first place, and why I want to get them working, is that I wanted a unified, improved experience. There's a very good reason why I don't let people select individual opera tracks in the installer, instead grouping them into one selection. 

It'd take going through the full opera with all the OTH opera tracks enabled (all of which come from one Tokyo Symphony Orchestra recording)  to see what I mean, but it's amazing to hear actual voices singing even roughly in time with the action on screen. And for every song but this one, that effect works. If I can't get this one working then I'd rather keep it broken and have a coherent alternative for the opera than replace one track with something from a different source. 

Believe me, this project has been in the works for years and we've been back and forth on the opera selections, and that was before we could even get anything playing in game. The ones we've found work 
*almost* perfectly with this one exception, and that's after a lot of work on Covarr and my parts.  The tracks we're using aren't changing unless someone magically comes up with another version of the opera that's fully voiced and has the correct timings. 

I honestly think, from actually having playtested it, that this version of the Aria can be made to fit just fine. It just sounds like the intro goes on too long. The actual vocals are perfect, they just come in late. And you've already said the track had extra unnecessary data so I guess I'm not understanding the problem.

**Comment by edale2** [comment]
The extra data was after the aria (so no help with editing the intro), I was thinking more "6 minute song ≠ 3:40 time slot," but I haven't tried the opera out in-game yet.

I do have an idea for shortening the into, assuming I can't just cut out a bit somewhere. Basically just cutting a chunk off the intro, then fading into the already playing music (so it doesn't just start blaring the song mid-note). 

I've still got to try playing the opera in-game with the unedited tracks to see where we stand before I even start editing though.

**Comment by Dizzy611** [comment]
Yeah, fading into it was a thought I had.

If you want to get the whole opera working with the MSU-1 for testing, just grab all the OTH tracks (including the disabled ones) and rename the disabled ones so they don't say disabled, stick them in the folder, and make sure you're using the latest ips.

**Comment by edale2** [comment]
OK, I'm gonna try, but this is gonna be HARD.

There's at least 2 minutes of extra music between the end of the first vocal section and the second.

First vocal section kinda lines up, at first, but really doesn't by the end.

On the plus side, there is NO variance in timing. Player has until the line is triggered to input the right choice, if they haven't input yet, it'll auto select whichever they have highlighted. If input earlier, it'll still wait until the correct time to start that section of lines.

I've already got the first vocal section lined up properly, but this is gonna be a much harder edit than the adding silence I did, because the music never stops, and I've gotta make the cut feel natural...

*edit- And you have until the second vocals are supposed to trigger to finish the dance, picking up the flowers, and getting to the top of the stage. If you get there early, you just wait until the appropriate time.

**Comment by edale2** [comment]
OK, maybe a bit easier than the ending edits. Even though I'm having to make a LOT more extensive tweaks between tests, I can test a LOT faster.

I'm also becoming GREAT friends with my stopwatch, lol.

**Comment by edale2** [comment]
https://mega.nz/#!nN5ywYiB!xuFH3RnAM_tAiRbLvL3fFvfYkJ_3R8JO-a8FU5Ng72k

To paraphrase the first line after the Aria finishes...
 ```LOCKE: Well done, EDALE.```

Already normalized.

Oh, did you see my fix for OST track 83 in #26?

*edit- CRAP. uploaded the test copy right before I got it perfect, rather than the perfect one itself., will have the new link up in a few minutes. 

*edit2- Link updated to the correct version of the track.

**Comment by Dizzy611** [comment]
Awesome! I'll have to test this out later today to see how it works. Also yeah, I saw your OST fix as well :)

**Comment by edale2** [comment]
Note, like I said, the vocals get more and more out of sync as the first part progresses, so it's not *perfect* perfect, it's just as perfect as that track can get for this timing.

**Comment by Dizzy611** [comment]
At this point I'm just glad that for the first time since the inception of
the project I can accurately claim that we have the entire soundtrack
supported and working with PCM audio. That's a pretty momentous milestone.

**Comment by edale2** [comment]
It's gonna get a little better shortly, just need to tie up a loose end or two and get something uploaded... :)

**Comment by edale2** [comment]
https://mega.nz/#!3Y5z2CYB!xS-w93r76EYrumncBC0rnKRqHvDGIXPNMvJBaq7UsXU

OST Opera tracks.

Timing on all of them is *perfect*.

Granted, they're not the greatest fidelity increase from the SPC sound, but the Final Fantasy purist (why are they modding the game again?) would be annoyed at their exclusion.

**Comment by edale2** [comment]
God, just looked up the OCR opera. Not touching that thing with a 10-foot pole, as far as inclusion in the actual game goes.

**Comment by Dizzy611** [comment]
Yeah, we had that PCMified at one point and then we realized there was no way we could fit it. It was the reason we added the "OTH" category.

I'm getting ready to test the OTH Aria right now. And awesome, congrats on getting the OST opera working :)

**Comment by Dizzy611** [comment]
Oh wow. Yeah, there are bits where the timing gets *ever so slightly* off but it's really nothing too bad, and it works really well nonetheless :) Awesome.

Closing this issue as fixed.

**Comment by edale2** [comment]
I honestly didn't think I'd get that as good as I managed.

-----

Also holy shit, While I was typing this message out my mom's leaving the house, and I hear her say, "There's a bike on the street behind my car.... There's someone going through my car!"

1 minute later, I'm running down the middle of the street, chasing the guy (who made it back on his bike before I got out there, but not before my mom bashed him with her 25+ pound purse, lol.), barefoot and wearing nothing but a loose pair of sweatpants and a torn-up t-shirt I only wear to sleep in. Even with him on a bike, it took him 2 blocks to get far enough ahead of me that I wasn't inches from stopping him.

At least the guy didn't try hitting my mom to get away (though that might have been because he saw me coming).

**Comment by Dizzy611** [comment]
Jeez, wow.

In any case, here's a video of your work in action.

https://www.twitch.tv/videos/181781859

Am also uploading to YouTube but that'll take a bit.

**Comment by edale2** [comment]
Wait, were you saying the timing gets slightly off on the OST opera tracks? Where? Very easy fix with these since it's *always* an adjustment of the length of silence at the beginning of the track.

**Comment by edale2** [comment]
I notice you using the Ted Woolsey Updated Opera in that video. What do you think of that patch so far?

**Comment by Dizzy611** [comment]
Not sure what you're referring to in the previous comment.
EDIT: oh, no, I was referring to the OTH tracks. 

As to the latter, I like it.

**Comment by edale2** [comment]
Ok, I was rereading the thread, and noticed you could have been referencing the OST tracks when you said they went slightly out of sync.

**Comment by Dizzy611** [comment]
At the time I wrote that bit in the qhimm thread you hadn't actually finished converting them yet. So I was talking about how I'd originally thought it wouldn't be possible to have OST opera tracks that sync properly.

**Comment by edale2** [comment]
Not talking about that, I was referencing this line:

```Oh wow. Yeah, there are bits where the timing gets ever so slightly off but it's really nothing too bad, and it works really well nonetheless :) Awesome.```

**Comment by Dizzy611** [comment]
Right, I was referring to the OTH there... As in the bit the issue was
originally about. That was a closure message.
