### ISSUE TITLE
Raft sounds

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#24]
Already said this in other threads, but here we go:

There's no music on the raft scenes, so there's no reason not to use PCM audio to improve that scene a bit (MSU-1 chip can only play one audio stream at a time).

https://mega.nz/#!nMo00JxS!Rorol76EJf_j8QgOD7Kq5pwZojQLvVVBZHDJ0rCXUVo

4 sets of white water rapids ambient sounds for you.

The one labeled OST is labeled so because it sounds almost exactly like the SPC audio. I'm using ff3-30-3.

**Comment by Dizzy611** [comment]
Nice. Will need to modify the installer a bit for this, but I think the easiest way is I'll add sound effects as their own track at the very bottom of the list. (And any other sound effects you do will just be downloaded along with that track, kind of like how the "Opera" selection downloads like 8 tracks :P)

**Comment by edale2** [comment]
I don't think there are any other sound effects that play without any background music as well (or at least ones that aren't also called somewhere else with music). I'll keep my eye out for any when I do a full playthrough at some point.

**Comment by edale2** [comment]
Hmmm... Possibly the seashore sounds on the first Island in WoR, will have to check if there are any places that effect is called while music is playing. Because that's another one easily enhanced. Though might take some work to find a clip that sounds desolate enough.

**Comment by Dizzy611** [comment]
Need to upload them to the /new folder but I've now put support into the installer for a "Sound Effects & Miscellany" "song" for the custom selection page.

**Comment by Dizzy611** [comment]
ff3-30-3 has been uploaded as "ff3-30" under OTH. Keeping this issue open, please post in here when you've finished with the other sound effect track you were going to do (WoR seashore waves I think?)

**Comment by edale2** [comment]
You liked ff3-30-3 best as well? Nice.

**Comment by Dizzy611** [comment]
Closing this one now that we have the waves one as well. I'll have to test them both in the installer of course. Will do that sometime over the next few days.

**Comment by edale2** [comment]
And now I see I was supposed to post in here with the seashore track, oops. Though I think the new issue got it to you just as fast, heh.

**Comment by edale2** [comment]
OK, So Barren Falls, the waterfall you jump off the top of in Sabin's scenario, apparently also uses track 30. and ff30-3, while sounding great for the rafting section, is a BAD fit for Barren Falls which should sound more like Niagara Falls for how big it's shown).

Gonna test the other tracks I made for this to see if any of them fit, but I might need to make a new one...

**Comment by edale2** [comment]
Ok, the one I labeled as ff3-OST fits perfectly for Barren Falls, and was passable for the Rafting section. I think it may be our best choice.

*edit-  Looks like track 58 (#30) plays as Sabin is washing ashore after jumping off Barren Falls. No music at the time, and track still fits beautifully.

**Comment by Dizzy611** [comment]
Alright, I might swap that out then :)

**Comment by edale2** [comment]
Some of these "one place only" tracks are turning up in a LOT more places, lol. 

Gotta admire Square's sound team for using the low-fidelity nature of the SPC audio to their advantage to get the same clip to work in so many situations.
