### ISSUE TITLE
Snes9x-msu does not resume properly after battle, instead the area music restarts.

### ISSUE THREAD

**Issue by Dizzy611** [Insidious611/DancingMadFF6#27]
I'm honestly assuming this is an upstream issue (incomplete/old MSU implementation?) because it works in Higan, bsnes-plus, and (I'm told) SD2SNES.

Ran into this while using snes9x-msu to stream a demonstration.

**Comment by Dizzy611** [comment]
Bug has been reported and the problem diagnosed, a fix is under way upstream. See above referenced issue.

Workaround is available in branch "snes9x-fix", but will not be merged into "master" due to not being necessary longterm.

**Comment by Dizzy611** [comment]
Fixed binaries for snes9x with msu support have now been posted. Closing issue and deleting workaround branch.

**Comment by edale2** [comment]
Might you provide a link to the location they're posted?

And is this an official Snes9x release, or a modification of qwertymodo's release?

**Comment by Dizzy611** [comment]
Same place you linked *me* to to begin with :P 

As to your question it's an odd one. Qwertymodo's work *is* an official snes9x release, even if the binaries are not his work is in their github. 

Please check the referenced bug for details as this bug is not in Dancing Mad.

For a quick link, https://dl.qwertymodo.com/snes9x.zip

**Comment by edale2** [comment]
I believe the most current official release of Snes9x is v1.54.1 and qwertymodo's modifications to allow MSU-1 audio will get merged into the officail release with v1.55.

I could be wrong, the posts I've seen about it are a few months old.

**Comment by Dizzy611** [comment]
I think you're right, yeah

**Comment by edale2** [comment]
Hmmm... I have no idea when that fix will make it's way to the RetroPie version.

The workaround was just commenting out four lines of the code, right? Could you please make me an IPS with all the current code, and include that workaround in it?

**Comment by Dizzy611** [comment]
Sure, first I'll see if the old IPS from the workaround branch is still in the git tree somewhere, but if not it's a pretty easy fix.

**Comment by Dizzy611** [comment]
https://github.com/Insidious611/DancingMadFF6/blob/snes9x-resume-fix/patch/ff3msu.ips

There you go. That also contains the fixes for #31 and #17.

**Comment by edale2** [comment]
Thanks greatly.

Found this just as I was about to post a new bug I found, lemme just double-check that it's not somehow fixed with this IPS first.

**Comment by edale2** [comment]
False alarm, Bug is really weird. It's not present in the MSU patch, it's not present in the Ted Woolsey patch, or the music player patch.

But if you have both the MSU and the music player patch, exiting the menu kills the background music in the returner's hideout, and the screen right outside the hideout (the screen that outside, but not on the worldmap) it plays the wrong song.

Again it's odd, because it's not there on any of the patches, only the combination of patches...

**Comment by edale2** [comment]
Actually, it doesn't kill the music, it mutes it, I can tell because it continues playing as if it hadn't stopped when you change rooms.

Like I said WEIRD bug.

**Comment by edale2** [comment]
Oh, that bug starts showing up after you get told to jump on the raft (if you go back in the hideout instead).

**Comment by Dizzy611** [comment]
Hmm, interesting. I noticed before that the way the game behaves when you enter and exit menus when you have the music player and my patch enabled is slightly different, oftentimes restarting a song unnecessarily or at least causing a slight hitch in the audio. Don't know that there's anything I can do about that.

**Comment by edale2** [comment]
I think the best bet is to make a note in the readme that

"the Ted Woolsey Music Player patch works with the Dancing Mad patch, but may cause some slight audio bugs/glitching during gameplay"

And leave it at that, unless we can get ahold of the coding for the music player patch, and spend more time on it than it's worth.

**Comment by Dizzy611** [comment]
Sounds like a plan.

**Comment by edale2** [comment]
Oh, I'm doing the rest of my current playthrough with just the Dancing Mad and Ted Woolsey, no music player, so I'm not going to find any more bugs related to combining those 2.

**Comment by edale2** [comment]
Looks like the fix finally made its way to the RetroPie version with the official release of Snes9x v1.55. There's no need for the resume-fix branch anymore.

**Comment by Dizzy611** [comment]
Awesome, I'll check the diff to make sure I didn't accidentally leave
anything important there, then kill it.

On Dec 4, 2017 1:26 AM, "edale2" <notifications@github.com> wrote:

Looks like the fix finally made its way to the RetroPie version with the
official release of Snes9x v1.55. There's no need for the resume-fix branch
anymore.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/Insidious611/DancingMadFF6/issues/27#issuecomment-348871148>,
or mute the thread
