### ISSUE TITLE
Installer Suggestion

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#29]
I believe it would be beneficial to include a "do not download" option for each track on the installer.

The main benefit would be users that only want to change 1 track in their previously made selections. As the installer is currently, the user would need to re-download every single tack for the entire game, when they already have most of them. This will especially be an issue for those with metered internet (this would allow them to download the tracks in chunks to stay under their usage cap as well).

**Comment by Dizzy611** [comment]
I could obviously only put this in the "Custom" section, but honestly I had been considering this anyway, especially since I already have code put in for "don't download this track" which used to be used for the opera.

**Comment by Dizzy611** [comment]
My biggest thing right now is trying to figure out what header I could put on a "Do Not Download" column that would be obvious and still fit in my sort of "max 3 letters" column header style. 

DND? NUL? NO?

As someone on a 750GB bandwidth cap myself (imagine how much of my cap I lose testing this installer repeatedly... >.<) I definitely understand what you mean re metered internet

**Comment by edale2** [comment]
from that pic of the new installer on quimm, it's max 4 letters now with "OCR2".

With that in mind, I'd go with "NULL", or possibly "SPC", since it'd be the SPC audio playing for those tracks.

**Comment by edale2** [comment]
Either way, I'd put a note on the page before the selector telling you that column means not to download the track.

**Comment by Dizzy611** [comment]
Have added support for an "SPC"/Do Not Download option in the latest commit to Master branch (b94566f6515c09a4a1b63f70bfec28ca1deaa2c5). Explained this option in the readme page's section on "Custom Track Selection". Seems to be working okay so far.

**Comment by Dizzy611** [comment]
Have now tested this and most of the other new installer features. I think we can call the installer feature-complete and tested for now. Just need to do some testing on the recent bug fixes for the patch.
