### ISSUE TITLE
New Track: The Desolate Waves

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#30]
https://mega.nz/#!2ZY0EKZC!ETdGaLK7_IUfYR9XlAlEktsnTW44W9_x9STnN7dZ7qQ

2 versions, I actually like version 1 better, but there's a slight buzzing sound throughout the entire thing that I couldn't get rid of.

Honestly, going through that part of the game, the desperate struggle to catch enough of the fast fish to keep cid alive (for no gain whatsoever except knowing he survives, seriously, return to him on the airship later in the game without Celes in your party, and his dialog still has him talking to Celes...), that track gave me chills.

The length of it also allows for a much more natural sounding patterns of waves than the 30 second loop of version 2.

Both are good though.

**Comment by Dizzy611** [comment]
Listening to -1 with headphones and not really noticing any buzz.

**Comment by edale2** [comment]
Buzz is an artifact of the slowdown I put on the track (80% speed IIRC), and at a really low frequency, does kinda blend in with the natural foam sounds though, which is why I didn't discard the track entirely.

Like I said, I have sensitive ears, lol.

**Comment by Dizzy611** [comment]
I think I'll go with version 1 anyway, I can't hear the buzz, or at least can't distinguish it from a "sea spray" sound, and like you said it sounds better overall.

EDIT: Yeah, ff3-58-1 uploaded. Closing, but will need to test this and the raft sounds in the installer.
