### ISSUE TITLE
Fixed up the Aria a LOT. Trust me on this. This you want to hear.

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#35]
http://fantasyanime.com/finalfantasy/ff6/saves/ff6save10Perfect_OperaHouse.zip
That save will get you right before the Opera scene.

I want you to load that up, advance to right before Celes walks on screen for the Aria (still in the dressing room). Create a savestate here. then walk on stage and go through the Aria.

Now that you've seen/listened to the Aria with my old version of OTH track 39, and everything's fresh in your mind, download this:
https://mega.nz/#!PEYCRAIT!MBIbJBK8pFvknn2T2PCXfpj5Z1cCA4dOa9JnBpw1Uns

Swap that version of the Aria in, and load that savestate up to watch it again with the new version of OTH track 39.

I'm not going to say anything, because I want your unbiased opinion on the new version, but trust me, you'll LOVE it.

**Comment by edale2** [comment]
Oh, I was also playing with the normalization on the track because it's so noticeably quieter for the vast majority of the song than the rest of the opera. The normalization doesn't quite work right because the ending is so loud in comparison. Since there's no SPC audio to contend against, I normalized it to a much higher volume. That one is normalized to -12dB, tell me what you think of the volume level as well the rest of the track.

**Comment by Dizzy611** [comment]
Alright, took time from my testing to try this out... Wow, the timing is so much better. Pretty much everything, including the animation lipsync, matches up perfectly. Pretty much the only thing that doesn't is the held note at the end, and even that is both A. impossible to get right unless I extended the amount of time that text is up and B. feels fine anyways, since it ends just as the star falls down.

I have *one* minor complaint. When switching from backstage to the stage, the music comes on mid-loud-bass-note rather jarringly. I'd suggest adding a short fade in in audacity maybe?

Volume level otherwise is pretty good. 

This legit gave me chills, watching the scene with the timing this spot on.

**Comment by edale2** [comment]
Hmm... Thought I got rid of that (by applying fading twice!) Lemme check real quick.

I actually thought the only place that didn't line up was the start of the 3rd stanza (from the choice right before the dance scene) though I got the timing to match backup by the end of that part.

I thought where the last line ended at the end was fine given she starts saying the last word just as the last word disappears of screen, she finishes the last note just as the chancellor's line starts, and the music finishes fading away with the screen fade-away.

Would it surprise you to know that not a single note of that song is playing at the original speed? Most of it is playing with a 10% speed-up, with some parts having closer to 5% and some as much as 15% speed-up (fun fact, audacity has a 'tempo change' option that can change the speed without changing the pitch).

And yea, I got chills the first time I sat down and watched the Opera with this track (where I wasn't avidly paying attention to the timing to make corrections) as well. And the second time... and the third time... and when I checked it with Ted Woolsey's Updated Opera... And when I checked it just now for that opening note, lol. Yea, I worked some magic on this one.

**Comment by edale2** [comment]
Yea, it was the bit where I joined the second part that i faded twice, forgot to fade the beginning entirely. I'll have a new one uploaded in a few minutes.

**Comment by edale2** [comment]
https://mega.nz/#!jZJGFJpT!ndxs8nvLo7-cM8b86w0ZFmcK-DajzOJZtLMf074FBnU
Fade added to the beginning, much better now.

Also... I didn't even try and match up the animations (honestly didn't even notice them) was just lining up the text to the vocals. But damn, I did hit the animations spot-on didn't I (again, except for the very beginning of the 3rd stanza, but they line up again by the second line)?

**Comment by edale2** [comment]
Might be time for a new Opera video. ;-)

I still can't believe I got that done that good. Wow.

**Comment by Dizzy611** [comment]
Have now uploaded this to the install path. Closing issue.
