### ISSUE TITLE
Victory theme plays on loop after leaving South Figaro during Locke's scenario - Possible LastTrack issues.

### ISSUE THREAD

**Issue by Dizzy611** [Insidious611/DancingMadFF6#37]
The victory theme will play on loop on the world map after leaving south figaro during locke's scenario, specifically it will do this after you have gotten into battle and won. The cause of this is probably that the victory theme is getting put in 0x1309 (LastTrack) when it shouldn't be, and the world map is likely being told to simply play whatever the "last track" was. 

Possible fix? Add a flag to denote that we're playing Battle or Victory themes, and if that flag is true, then do not store the current track in LastTrack. We already have code to handle the battle theme specially so I can piggyback this on that, but I will need to add Victory Theme to special handling as well.

First encountered during final beta testing push, see issue #36.

**Comment by Dizzy611** [comment]
Committed a potential fix to a new branch. Will need to rig up a save to test it, which will be somewhat difficult as there are few places to save in Locke's scenario, and a savestate would not necessarily be useful due to needing to test with 3 seperate ROMs (unmodified, current master, branch fix), and a save state from one potentially "polluting" the important areas of RAM of others.

**Comment by Dizzy611** [comment]
Cannot reproduce this bug in bsnes-plus, which is making testing difficult.

**Comment by Dizzy611** [comment]
Seemingly unable to reproduce it in snes9x on my PC as well :/ This is an odd one.

**Comment by Dizzy611** [comment]
Will try reproducing later in lr-snes9x on the pi again. If I can't reproduce it there, I'm going to have to just assume this fix will work and merge it into master for now, but leaving this issue open as I won't be able to confirm it.

**Comment by edale2** [comment]
Trying to reproduce.

Oh fun fact, be in a solder's uniform when you save Celes for some lols and  GREAT reference.

**Comment by edale2** [comment]
OK, using the master-branch IPS (which IIRC doesn't have the workaround for resume-support in lr-snes9x, since they're not updated with qwertymodo's fix yet), I cannot reproduce this. In  the South Figaro worldmap area it just continues playing "Under Martial Law." 

If you could update the snes9x resume-support fix branch with the new track 51 code I can test further.

*edit- Actually... it's resuming music after battles properly, maybe I don't have the master branch on this... retesting...

**Comment by edale2** [comment]
OK, definitely with the master branch this time, can't reproduce.

It might have been a one-time glitch. lr-snes9x isn't nearly as stable as the other snes9x builds for the Pi (it's completely frozen my Pi3 a few times during my playthrough, requiring unplugging to reset, couldn't even SSL in to soft-reset).

Also, music still seems to be resuming properly after battle,is the resume-workaround in the master branch now?

**Comment by Dizzy611** [comment]
Temporarily, yes. 

I wouldn't count on it staying in there, it's basically only there while I'm testing with the Pi, for my own convenience. :P

I wouldn't normally pollute the tree like that but it's literally a difference of 5 semicolons, so it's easy to put it back to the proper behavior either when I'm done testing or when lr-snes9x catches up with current snes9x GIT code.

**Comment by Dizzy611** [comment]
Closing this as unreproducible.
