### ISSUE TITLE
"Select a Scenario" screen plays the last music/sound effect played, instead of silence, until you enter and exit a menu.

### ISSUE THREAD

**Issue by Dizzy611** [Insidious611/DancingMadFF6#38]
This may be an instance of Track 51 in the normal game's code. I will have to run the game through a debugger to check. If so, I might have to figure out where the current area is stored in memory and simply have my track 51 code do silence if it's the moogle scene, as this should be a unique area.

Encountered during Final Beta testing (see issue #36)

**Comment by Dizzy611** [comment]
Can't figure out where the current map/area is stored in memory by looking at currently existing RAM maps or poking about in the debugger. :/ This may be a hard bug to squash.

Am trying to find some other way of figuring out that we're currently in this scene.

Honestly if I can't fix this one I don't consider it a huge loss. It's a tiny scene and a minor immersion breaker at worst.

**Comment by edale2** [comment]
Reproduced.

Don't believe this problem existed before the track 51 fix. Again, odd that entering/exiting the menu properly silences it if it is an in-game track 51 call.

track 51 might have been what was meant to play at this scene, but the track never got implemented, lol.

**Comment by edale2** [comment]
OK, Found a nifty little tool: https://www.romhacking.net/utilities/1238/

Part of the Interface Has the Hex value of the location for each map, along with a description of what that map is!

[$051] is the address for the Rich Man's House in South Figaro, for example. (identical map at [$052], unlabeled...)

I'm looking through the list to see if any of them are labeled for this particular scene, but I've seen 2 or 3 possible ones it could be if none of them are labeled.

**Comment by edale2** [comment]
Found it!
[$009] Choose a Scenario

Have no idea how I missed it the first time I went through the list...

**Comment by Dizzy611** [comment]
I'll have to figure out where in the actual RAM these values are stored but knowing what the values *are* internally is a useful step in that process, as I can use e.g. cheat utilities to scan for these values. So thanks, this could prove useful.

**Comment by edale2** [comment]
Well it looked like at least 3 of the utilities on romhacking.net could locate the maps and such, I'll try glancing through and see if i can't find the info on where they're located in one of them.

**Comment by edale2** [comment]
https://datacrystal.romhacking.net/wiki/Final_Fantasy:RAM_map
A full RAM map of FFVI SNES, they have a full ROM map as well.

I can't really make heads or tails of the info, but searching "map" does give several results that might be what you're looking for.

Funny how the guy that knows how to use this stuff has trouble finding it, and the one that can't make heads or tails of the raw data has no trouble finding it, lol.

**Comment by edale2** [comment]
Yea, the editors all just edit the ROM, they don't seem to deal with the RAM...

**Comment by Dizzy611** [comment]
I assume you meant to link https://datacrystal.romhacking.net/wiki/Final_Fantasy_VI:RAM_map, since what you linked is for the original NES final fantasy. I have that in my references, the FF6 RAM map that is. Problem is, that's *not* a full RAM map. Not even close.
It's not even 5% of the RAM the game actually uses. It's mostly a SaveRAM map.
It's notably missing any mention of the current loaded tileset, the currently loaded map, or the current playing music (the music values I tracked down myself through debugging when I first started this project, I later found them referenced here https://www.ff6hacking.com/forums/thread-1408.html but that still doesn't have everything.)

The problem is that there's a lot of work that ends up needing to be re-done because people don't document what they find :P I might look into the source code of FF6LE to see where it gets its information from though, that might help.

**Comment by edale2** [comment]
Odd... must have grabbed the URL from the wrong tab, lol.

Just did some more digging:
http://www.ff6hacking.com/wiki/doku.php?id=ff3:ff3us:doc:game
from the event editing tutorial (http://www.ff6hacking.com/wiki/lib/exe/fetch.php?media=ff3:ff3us:doc:game:ff6_event_editing_tutorial.zip):

----

We're gonna do some simple map-loading excercises. Sound fun? OK bear with me, we can't just hop into the sophisticated stuff. Now, open up that Event Dump and wait the 20 secs it takes for it to load in notepad. Okay this is probably a lot more friendly than the hex editor but it's still easy to mess stuff up if you get the wrong info (which is your fault xD).
Now to find something within the game that you want to edit, it's best to do CTRL + F and search for the text that is near the particular event you're looking for!
We're gonna edit the maps that load in the very beginning of the game, where the text "Long ago starts.
So, if you still haven't, go ahead and click CTRL F and type 'Long ago,' you can just stop typing there and it should find alot of text with "long ago".  The first 1 should NOT be it, it should take six searches of Long Ago for it to find the map loading sequence! 
You should see this:
CC/985F: 6B    Load map $0017 (Narshe, mountaintop (WoB / "Long ago, the War of the Magi...")) instantly, (upper bits $2000), place party at (18, 25), facing down
If not, exit out of the file and re-do it all! It's there ha.
Okay now what you're looking at is offsets, the 6B command (loads a map) and then what I call comments (C++ does stuff to ya). 
In this case, the comments are "Load map $0017 (Narshe, mountaintop (WoB / "Long ago, the War of the Magi...")) instantly, (upper bits $2000), place party at (18, 25), facing down"
Comments are pretty much the secondary reason this text file was made! It tells you what the hex is doing at that paricular part.

----

The whole first section is about loading map stuff, it might have the hex location you need.

**Comment by edale2** [comment]
Found it!

---

Notable Locations in RAM

$000520-$000540                 Current Location Data

---

from the FF3Info V1 document on that site I linked to a min ago: http://www.ff6hacking.com/wiki/lib/exe/fetch.php?media=ff3:ff3us:doc:game:ff3info.zip

At least I _think_ that's it.

**Comment by edale2** [comment]
Yea, if that one's not it, then I give up for now, getting a headache from digging through all this code. Hopefully that last one it, and if not, hopefully what I've dug up is enough for you to figure it out.

**Comment by Dizzy611** [comment]
You've definitely given me enough to start from, thank you :)

**Comment by edale2** [comment]
Is there anything I can do to help you track this down?

I tried playing with the debugger in BSNES plus, but couldn't really figure out what setting did what (well, I know _some_ of them), and definitely don't know which setting lets you check the RAM you're working with (there were like 6 or 7 things you could monitor in there!). If I know the basic settings to use, I might be able to help...

**Comment by Dizzy611** [comment]
What you've given me so far is enough to get a start on it myself, I just
haven't had time yet.

If you want debugger tips, In general, what I do is in the debugger window
set a breakpoint on execute (that's the X checkbox) of address c50182,
which is part of the track loading routine for the SPC and is where the
jump into my code takes place. I then open the memory editor and
disassembler and look at important memory addresses to see what data is in
them, and watch how my code branches to make sure there aren't any logic
errors. Understanding the debugger without understanding SNES assembly
language is hard though.

**Comment by edale2** [comment]
I'm hoping one of the emulators has a debugger that would let me narrow down RAM addresses in a manner similar to Cheat Engine.

You know, search for a known value, do something to change that value and search the previous results for the new value, repeat until the needed location is located. Which in this case would be searching for the locations that match the map ID for whatever map I was on, changing the map, then searching for the new map's value. Would take like 5 minutes to find like that.

**Comment by edale2** [comment]
Playing around with Zone Doctor CE: https://www.romhacking.net/utilities/1237/
 (very similar to the other program, but seems to have a bit more features)

It looks like on the maps, you can actually examine the code of each event and NPC.  There's a fair amount of code on the select a scenario map, especially on the NPCs.

**Comment by edale2** [comment]
Well it turns out Snes9x's cheat search function works almost exactly like Cheat Engine (though much less user-friendly), I'm not sure if the values it's searching are the RAM, but I would assume so, and if so, then the address that the current map data is located in seems to be 7E0082.

There were a number of addresses that seemed to always list the current map, but that one is the only one that still matches up on the worldmap, and it's the only one to change when you enter a battle (rather than staying on the value of the map you were on before entering battle).

**Comment by Dizzy611** [comment]
That looks like a SNES RAM address to me. I'll have to see if that's
populated when the Play Track routine is called. If so, you may have found
us our golden ticket :P

**Comment by edale2** [comment]
I did notice one problem, on the worldmap it has a value of "0". This is fine, as the WoB worldmap _is_ map ID 0. The problem is the WoR worldmap is map ID 1, and that location still reads "0" in WoR.

Like I said though, there were a number of addresses that seemed to follow the current map ID, so it's very possible one of those is the specific address you're looking for. If 7E0082 isn't the value you need, let me know and I'll take a screenshot of the other addresses.

----

*edit- No values that read as 1 on the WoR worldmap accurately list the map ID anywhere else... very odd.

Oh, and I was searching a 2-byte strings, as there are more than 255 maps.

**Comment by edale2** [comment]
Oh, and checking the code for the Rich Man's house in Zone Doctor CE, the draft sound in  the hall... it's only supposed to play at 0.03% volume, lol.

**Comment by Dizzy611** [comment]
That may be why it bugs out. My code subtracts from the given volume value in order to bring things in to a more sane level for the MSU-1 (which tends to be a tad loud, even the fixed versions). Since it's an 8 bit value, if you subtract too much you can easily roll around to a large number. And with the base value being so small... I have checks against this but 0.03% is... really pushing it, further than I thought the game would.

**Comment by Dizzy611** [comment]
Alright, having finished my testing I'm taking a look at this one again now.

**Comment by Dizzy611** [comment]
Good news, it looks like that memory address does hold the current map when in my routine. So I can most definitely use this to tell what map I'm on during music loading.

**Comment by Dizzy611** [comment]
Alright, thanks to @edale2's work I was able to come up with a potential fix for this issue, I'm giving it some testing now before pushing it to a branch.

**Comment by Dizzy611** [comment]
Okay, I had a little trouble with this one, for a few reasons.

1. It wasn't calling my normal "load a track" code at all, so I had to stick a bit of a hacky subroutine into the "play command" code (otherwise used mostly for switching subsongs in dancing mad).

2. During the part where it actually calls into the music code in the switch between a scenario and the select a scenario screen, it's actually not on map 9, it's on map 46 (which appears to be blank). Hopefully this map isn't used for any other fade-to-black transitions or if it is, it's not used in a way that will cause undefined behavior with my code.

3. Zeroing out playtrack/playvolume/currenttrack didn't stop it from continuing to play, because it still never hits my MSU-1 code so it never hits the bit that tells the MSU-1 to silence itself, so I had to add code to specifically stop the MSU-1 and zero out its volume, to this handling area.

It seems to work now, correctly playing silence in the Select a Scenario room. I'm going to need some further testing on this, but I've burnt myself out on testing for a bit with the rush to test everything else. Obviously, test the select a scenario thing, but also, if you can think of scenes that fade to black but *aren't* supposed to end up with silence when fading back in, please test it with them and make sure you don't get silence. That would be the expected undefined behavior.

Please also test what happens if you go to the select a scenario screen and an SPC track was playing before the select a scenario screen, instead of an MSU-1 track.

I've done most of my testing with Locke's Scenario because I happened to have a save right before entering South Figaro cave at the end of that, so testing other transitions into Select a Scenario is probably also prudent.

This is super experimental ATM so I'm not going to push this to the master branch. It is based off the master branch code though.

Also, @edale2, please test if this fixes your old man's house wind problem (it should play the SPC track instead).

The experimental IPS patch is here: https://github.com/Insidious611/DancingMadFF6/blob/select-a-scenario-fix/patch/ff3msu.ips?raw=true

**Comment by edale2** [comment]
[ff3.zip](https://github.com/Insidious611/DancingMadFF6/files/1444637/ff3.zip)
Save right before fighting Ultros and getting to the select a scenario screen for the first time.

Track 30 continues to play on the select a scenario screen using that patch.

**Comment by edale2** [comment]
Without track 30 in there (so SPC audio), it fades to silence like normal.

BUT, it's a really slow fade-out into silence, so that might be part of the problem, that it's not just stopping the music to get silence, but fading the sound to nothing.

It might actually still be playing the track like normal, but at 0% volume the entire time you're on the scenario selection screen.

Maybe it's hitting that same rollover you mentioned could be causing the problems with the wind sound in the Rich Man's house from it being set to 0.03% volume.

**Comment by edale2** [comment]
Still plays PCM audio in the Rich Man's house, and it's still buggy in how it plays it.

I noticed a "Locke scenario fix" branch, what's that one for? - nevermind, I found the note in the branch on what it was supposed to fix.

**Comment by edale2** [comment]
Looking at the coding in Zone Doctor, it looks like the wind sound isn't suppose to start at all until you are standing on the step right outside the room with the passage (at 0.03% volume), with a second line of trigger's half way through the room to up the volume to "$30", then setting it to "$60" right next to the bookcase with the passage behind it.

*edit- nope, it plays at 0.03% volume in the entire house, the trigger outside the door to the room is probably to lower the volume as you leave.

**Comment by edale2** [comment]
Silence on the select a scenario screen after Locke's scenario.

**Comment by Dizzy611** [comment]
Hmm... yeah if it's doing a volume slide, I'm not handling those. The game does most of its volume changes by just asking to play the same track at a higher or lower volume.

And by what you said my hacky fix might only be triggering for the Locke scenario. Damn, this needs more investigating.

I might postpone this one until after the final beta release, maybe do a hotfix once I've nailed it down.

locke-scenario-fix is for #37, was never able to get it to reproduce in anything with a debugger so it's untested.

**Comment by edale2** [comment]
So in other words, it can't be fixed until the fading issue gets worked out then?

So hopefully you can find a fix for getting the SPC audio to play instead there, or we're gonna have to drop the wind track entirely.

**Comment by edale2** [comment]
Music continues to play after the end of the Terra/Edgar/Banon scenario, I'll have a save up in a few minutes.

**Comment by edale2** [comment]
[ff3.zip](https://github.com/Insidious611/DancingMadFF6/files/1444779/ff3.zip)
Save right before the end of terra's scenario.

**Comment by edale2** [comment]
[ff3.zip](https://github.com/Insidious611/DancingMadFF6/files/1445033/ff3.zip)
Save right before the end of Sabin's scenario (enter town and hop on ship).

Waves PCM track continues to play in the scenario selection screen after finishing Sabin's scenario.

And with that save, you should now have saves before every instance of the select a scenario map. Should make testing things out a bit easier.

**Comment by Dizzy611** [comment]
Thanks, that definitely might help me put in workarounds.

**Comment by edale2** [comment]
Yep, it definitely might possibly have a chance of potentially helping you. ;)

**Comment by Dizzy611** [comment]
Going to get back to working on this tomorrow likely, now that I've released the final beta (see https://github.com/Insidious611/DancingMadFF6/releases/tag/20171108)

**Comment by Dizzy611** [comment]
Confirmed fixed on Terra's scenario.

**Comment by Dizzy611** [comment]
Confirmed fixed on Sabin's scenario.

**Comment by Dizzy611** [comment]
Confirmed fixed for initial Choose a Scenario screen after Ultros

**Comment by Dizzy611** [comment]
Confirmed fixed for Locke's scenario! Well, even if the fade-to-zero workaround didn't fix F-Bomb's Shadow scenario bug, it fixed this at least!
