### ISSUE TITLE
BUG: Dancing mad track 3 - 2 PCM tracks playing at same time

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#40]
Kefka's 3rd form, I have both tracks 102 and 103 playing.

102 will play while the game is paused, 103 will only play when it's unpaused.

**Comment by edale2** [comment]
IIRC this didn't happen before, I remember testing it after the last fix for the tracks not playing without PCM audio.  This might be a legitimate in0game track 51 call.

**Comment by edale2** [comment]
hmm... track 103 might actually be the SPC audio, not the PCM...

**Comment by edale2** [comment]
Audio fixes itself on Kefka's 4th/final form.

**Comment by edale2** [comment]
ok... forget this... I FTPed into my Pi and apparently I don't have all the tracks for Dancing Mad in there, no track 101 or 102, but has the other two tracks...

Which is odd, because I have a different directory I use for testing, rather than the one I'm using fofr my playthrough...

**Comment by Dizzy611** [comment]
Woops. Sounds like you triggered the fix for #31

**Comment by edale2** [comment]
Yep.

**Comment by edale2** [comment]
Ah, I had run out of HDD space on my Pi, that probably caused the problem

**Comment by Dizzy611** [comment]
Yeah this ROM hack is not exactly space-light.

**Comment by edale2** [comment]
I have a 128 GB SD card in there, lol.

Fun news, Running out of HDD space like that? Yea, my save and savestate are both corrupted.

I can just use the godmode save to get back there because I was right before Kefka, but frankely, the godmode settings are a step down in dmg output for what I had managed, lol.

**Comment by Dizzy611** [comment]
I've been taking backups of backups of backups. Mind you, I'm also not
actually hosting my ROMs on the Pi itself, I have a fileserver with a
proper hard drive that it's using over windows networking. The only things
on the SD card are Retropie itself and the saves

**Comment by edale2** [comment]
Yep, Kefka's fight goes smoothly with all the tracks actually there.
