### ISSUE TITLE
Re-do Sid Selection with new OCR and OTH mixes in mind.

### ISSUE THREAD

**Issue by Dizzy611** [Insidious611/DancingMadFF6#41]
Basically this means, I should go through all the tracks again and see which one I prefer, for a second time, with the new OCR2 mix and the OTH tracks, *and* keeping in mind my experiences doing a full playthrough (there's a few tracks I "selected" that fit worse than I thought. for example, the one that plays during the snow fields battle)

**Comment by edale2** [comment]
and that's when I realize that along with my loop notes, I also lost my list of picks, so I have to go through everything again too, lol. Was already planning on that because of OCR2, but still...

**Comment by Dizzy611** [comment]
https://gist.github.com/anonymous/3308039f78cc4aa405a532a4142f618c the linked gist is where my progress on this is going so far. It's taking quite a while on each song to decide, especially with so many sources. I also feel like I'm going to have to go back afterward and make sure I'm making the right decisions. :P

**Comment by edale2** [comment]
You know, I started to go through and reselect everything when you first made this thread, got 10 tracks in, and forgot all about it, lol.

Having fun reading your notes on the songs, heh.

**Comment by Dizzy611** [comment]
This is currently blocking issues #56 and through that, issue #49.

**Comment by Dizzy611** [comment]
Going to get back on this on the 1st.

**Comment by Dizzy611** [comment]
Finally done. You can follow my decisions in the GIST, which will eventually be made a new text file in the docs folder (and the old one will be renamed but kept for reference/posterity). Having done this, have also mostly finalized the XML file, so I can now get back to making the installer use the XML file.
