### ISSUE TITLE
Minor Optimization: and/cmp/beq to and/bne

### ISSUE THREAD

**Issue by Dizzy611** [Insidious611/DancingMadFF6#42]
This is some 65816 asm craziness right here.

Some background is necessary:
the CMP (compare) instruction is implemented as a sort of virtual subtraction, operating on the processor status registers (P) without modifying the accumulator (A). This ends up setting the "zero" flag if the two things being compared are equal, clearing the zero flag if they're not, and setting the "carry" flag if the accumulator is greater than or equal to the operator. 

So, since they're mostly meant to be used with CMP, BEQ (branch if equal) and BNE (branch if not equal) are actually "Branch if Zero Flag Set" and "Branch if Zero Flag Clear".

With this in mind, when I use AND to check flags (mostly used for MSU status), doing a CMP against these flags after ANDing them and then a BEQ would seem unnecessary. If the flags are not set, the result should be zero, so the zero flag would be set (confusingly, triggering BEQ). If the flags ARE set, the result should be non-zero, so the zero flag would be cleared (confusingly, triggering BNE)

I should be able to save at least 4 cycles doing this. There are 7 instances of lda/and/cmp/beq in my code, so that's 28 total cycles (maximum) saved. 

However, I'm not 100% sure this will work as it seems rather odd and off the beaten path. So I'm putting this up here as an issue instead of just changing my code as if this didn't work it would break nearly everything.

**Comment by Dizzy611** [comment]
Alright, have a preliminary test of this in the "and-cmp-beq-optimization" branch and it seems to be performing without issues. More testing is needed.

**Comment by edale2** [comment]
What needs testing in this build? Any areas in particular?

**Comment by Dizzy611** [comment]
Just general "do things function". The change, while small, is pretty fundamental to a lot of checks including "Does the MSU-1 exist", so if it breaks it should generally break immediately and noticably. Other things... Make sure tracks still resume after battle, as well, and that SPC sound effects and music still play properly.

**Comment by edale2** [comment]
Overworld music doesn't resume correctly after battle. (tested right before Opera, about to test Opera)

Does this build have the resume workaround in it?

**Comment by edale2** [comment]
Oprea seemed to work fine.

And I was right, the other tracks besides the Aria in the OTH version need some work done on them...

**Comment by edale2** [comment]
You know I've read the explanation over and over, but I just can't wrap my head around exactly what this optimization is actually doing... I think I need a flowchart to actually understand this, lol.

I'm also unsure of the benefit. Do the saved cycles give you more leeway for implementing fading when you figure it out? Help prevent slowdowns? What does it actually _do_?

**Comment by Dizzy611** [comment]
The saved cycles may help prevent some slowdown primarily during track
loading, as the  comparisons in question mostly check the sanity of the
state of the MSU-1, making sure its doing what the state stored in memory
thinks it's doing and updating memory if not.  This may help when it comes
to fading because when Madsiur tried to implement fading he reported
lagging on scene change. If the amount of cycles expended by the actual
track loading routine is lower, it lowers the amount of total cycles spent
between fading and track change, during scene transitions. Also, it's
generally good coding practice to optimize where you can.

It's particularly relevant during checking for track load errors (which is
how it falls back to SPC when a file is not included), especially on the
SD2SNES. The code gets stuck (unavoidably) in a loop doing these
comparisons over and over again while waiting for a track to load.
Emulators cache the existence of tracks and are usually running on fast
storage, so this happens instantly, with the code only doing a single
and/cmp/beq or and/bne. The SD2SNES has to rely on SD cards which are much
slower and it also has to rely on interrupts from the SNES CPU which slow
it down further. As such it will run that loop tens if not hundreds of
times. These cycles add up, quickly, with 4 extra cycles suddenly becoming
400 or 800 or 1600, which at the SNES speed of 3.58MHz is an appreciable
fraction of a second in computational terms.

That said, it is a relatively *minor* optimization, all things considered.

Flowcharting how this optimization works is beyond my capabilities as I've
never been a particularly good teacher. Basically though, it's a
combination of quirks of boolean logic and quirks of how comparisons work
on the SNES CPU. And no, the snes9x resume workaround is not in this branch.

**Comment by Dizzy611** [comment]
To address the other thing you brought up, this will *not* do anything to
give more leeway for the NMI (where the fading has to be implemented) as
this code is not part of the NMI. That said, if this works it may give me
ideas on how to optimize the NMI.

**Comment by Dizzy611** [comment]
Ugh. My email client murdered the formatting on those replies. My apologies.

**Comment by edale2** [comment]
Dancing Mad and the ending both appear to work properly with this.

**Comment by Dizzy611** [comment]
Can you check to see if music is properly resuming after battle now in this branch? You mentioned that the upstream snes9x bug has been fixed on the version you're using.

**Comment by edale2** [comment]
Music resuming properly with this branch's IPS verified.

I don't think I checked the select a scenario or Figaro castle sections but other than that, I think I've tested this over most of the problematic areas of the game, and everything seems to work.

**Comment by Dizzy611** [comment]
Alright thanks, I'm going to merge this optimization into master then. Closing.
