### ISSUE TITLE
Awakening Alternate OCR Loop (edale2 ver)

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#43]
So I finally got around to downloading ALL the new tracks (basically everything in the 'new' directory, I had only grabbed the tracks I was using for my playthrough before), and going through them again with my experiences playing the game in mind, and to actually check out OCR2 (and because I lost my list of picks a few days ago).

I got up to track 5 "Awakening", and hit a dilemma.  You see, I had picked the OCR track for my playthrough, but that somewhat distorted note at the very beginning was a bit off-putting every time the song came up, but I still liked the overall track much better than the other options.

Qwertymodo's version was just the first part, so it still had that distorted note, and was cut down to the first minute and a half or so.

I actually liked the second chunk (the bit that came right after qwertymodo cut the track) MUCH better than the first chunk, as it's basically the first chunk with a bunch of extra instruments added in.

So I popped the FLAC of the Balance & Ruin release of the track in Audacity, cut out the first verse entirely, so it _starts_ at the second verse.

Then I hit the problem of no loop points. and I mean NO loop points.

I should mention, I've gotten a LOT better at audio editing since I started helping with this, I've constantly found and learned new tricks for how to get things done in different ways (as you've already seen with the Aria track).

The very end of the track, as it fades out, lightly plays the first few notes of the song, which essentially match up with, but are different from the ones that start the second verse.

I copied a 6ish second chunk of the beginning, matching up with those fading notes (it's a long fade-out, and I made sure to include the entirety of it), and pasted them into a new track, lined up to perfectly match the bit at the end, but _didn't_ apply a fade-out to it, instead I applied a fade-IN. (I also made sure EVERYTHING joined up at null-crossings, so the merger would work seamlessly), then I merged the tracks, and looped it to the exact sample my copied chunk ended at (again, a null-crossing). This basically created the effect of the beginning notes overlapping the ending notes, as they cross-fade into each other. It makes those few fading notes sound like the beginning of the opening (of the second verse of the song, where I started it) fading in, and it sounds like it was always meant to do that.

This shit follows the saying "if you've changed something properly, a 3rd party won't be able to tell an edit was made." 

https://mega.nz/#!zYpl2bDA!8O9_6RksuMpXKuXKNSt-jlZev4Synn_JHTeM1iRr2NM

OCR3? lol, Probably another OTH track (because it's distinctly different from both other versions of the song already included, but there's nothing inherently wrong with either). I know the installer's frozen for the beta release, so including it's probably gonna be a post-release hot-fix or something; but I made it, I'm using it, so I'm sharing it.

**Comment by Dizzy611** [comment]
Making a note that this has been added to my local copy of the data files and has already been taken into consideration for the new developer selection.

**Comment by Dizzy611** [comment]
Closing for same reasons as I closed #44.
