### ISSUE TITLE
Installer testing log

### ISSUE THREAD

**Issue by Dizzy611** [Insidious611/DancingMadFF6#45]
Doing tests of/minor work on the installer in preparation for final release, logging what I've done here to keep track.

Done so far:
- Tested packageinstaller.bat  - OK!
- Tested custom track selection page. - OK!
- Tested ability to load presets on custom track selection page. - OK!
- Tested ability to choose not to download tracks on custom track selection page. - OK!
- Synced installer directory IPS with current master branch. - OK!

In progress:
- Testing install of "Developer's Recommendation"
- Testing install of sound effects

To do:
- Test install of FFT, SSC, OCR, OCR2, OST presets.
- Test install of custom selection.
- Test what happens if you select *no* tracks to install (patch only run)
- Test selection of all available OTH tracks.
- Maybe add sample of Kefka's laugh to start of installer just for the fun of it?

**Comment by edale2** [comment]
No no no, Kefka's laugh should be the notification the installer has finished, not the start of it. ;-)

Or better yet, why not both!

**Comment by Dizzy611** [comment]
Potential bug in the installer noticed: If you install to a folder that already has an install in it the installer may crash for some reason. I think it has to do with the IPS patching process, not sure though.

**Comment by Dizzy611** [comment]
Tracked it down, really simple bug, just need to check for and delete any instances of "ff3msu.sfc" or "ff3.sfc" in the destination folder before doing the copying and patching. Fixed in c88fbbb (fix for said fix in d8d834b3). May cause issues if someone sets their source ROM as a file named "ff3.sfc" or "ff3msu.sfc" in the destination directory, but I suspect this is unlikely. Will probably caution against it in readme anyway.

**Comment by Dizzy611** [comment]
Newly done:
 * Testing FFT, OCR, OCR2, Developer recommendation, sound effects - OK!
 * Test custom selection install - OK!

To do:
 * Test SSC, OST
 * Test selecting no tracks to install
 * Test selection of all available OTH tracks
 * Kefka laugh.

**Comment by Dizzy611** [comment]
Newly done:
 * Test selecting no tracks to install - FAIL.

Bug (somewhat predictably) when selecting no tracks to install: Hangs on "downloading 0/0". I'll need to put special code in to handle this.

**Comment by Dizzy611** [comment]
Fixed above bug in 1a448f9

To do:
 * Test OST
 * Test selection of all available OTH tracks.
 * Kefka laugh.

In progress:
 * Test SSC

**Comment by Dizzy611** [comment]
Kefka laugh implemented when downloading/patching finishes :P

To do:
 * Test selection of all available OTH tracks.

In progress:
 * Test OST

Newly done:
 * Test SSC
 * Kefka laugh

**Comment by Dizzy611** [comment]
On the home stretch.

In progress:
 * Test selection of all available OTH tracks.

Newly done:
 * Test OST
 * Testing/fixing of Kefka laugh

**Comment by Dizzy611** [comment]
Installer testing officially complete! Gearing up for release now (you'll notice the "new" directory just disappeared, everything has been moved from there to ff6data/)
