### ISSUE TITLE
Alternate Opera Renditions

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#46]
https://mega.nz/#!GMIA2RIY!xW08WOEHbTsNAmbL0oTZMISjpMCbmPTxC2FUF4NTXFU

This is the version of the Opera from the "More Friends: Music from Final Fantasy" album.

The male vocal parts aren't the best match, but the Aria... Make sure you're using the Ted Woolsey + Updated Opera patch when trying this one out, that's all I'm gonna say on it. Other than the fact that it took me over 5 hours to get the Aria timed properly, in some cases modifying the timing for every other word in a line...

---

Remember awhile back when I made the Black Mages tracks, I said there was a 4th FFVI cover, but it was a vocal track? Well, it turns out it's _their_ version of the Opera. 

I'm gonna try converting it, and see if it works out in-game. I really hope it does, because it's a really good version (among other things, the narration is vocalized).

**Comment by edale2** [comment]
Was just wiki-surfing FFVI music stuff, and discovered something I didn't know that's kinda interesting. The band's leader is Nobuo Uematsu, the producer and composer of FFVI's music.

Guess that explains why their tracks are so good, lol.

**Comment by Dizzy611** [comment]
Hmm. I don't really know that I want to make *another* "OTH" column in the custom selection page, and I would need to since the current opera stuff is under "OTH" already. That's the only problem I have with this. Other than that, awesome work.

**Comment by edale2** [comment]
And after TBM version, it would be the OTH(OTH(OTH)) column, lol.

**Comment by edale2** [comment]
ACK! I just realized, I hadn't normalized this version of the Opera, to make the editing easier, and I forgot to normalize them  when I was done editing, before uploading.

Can you run your script on those, or should I normalize and reupload?

**Comment by edale2** [comment]
It looks like there are at least 5 different voiced versions of the Opera. In both English and Japanese.

- "More Friends: Music from Final Fantasy" version
- The Black Mages version (which was the first release ever to have the complete uninterrupted Opera)
- Balance & Ruin
- Whatever version you already had.
- Game Music Concert 4's version

I was actually thinking of trying to convert them all eventually (except maybe B&R, what little I listened to of it didn't sound even close to how the Opera's supposed to sound, but I might have just listened to the wrong parts).

*edit- and I also just realized I have FLAC for all of these versions already, so it's literally just doing the editing left to accomplish this, but that's a good 3-5 hours of work for each version...

*edit-Looks like the version you're using for OTH _is_ the Game Music Concert 4 version.

**Comment by edale2** [comment]
https://mega.nz/#!6MB0mTbA!351WXB6xDpbAwaC5E025-i3j9Mzur5UgCN4aaI8fwRE

OK, the "More Friends: Music from Final Fantasy" tracks are normalized now, and track 70 is actually looped (apparently I forgot to loop it when I was making those).

And as a bonus birthday gift to myself (even though my birthday ended 4 hours ago...):

**Comment by edale2** [comment]
Well... don't you just love when you accidentally post something you're in the middle of typing...

Anyways, as a bonus: 
https://mega.nz/#!KJRGVKKK!7z_LdxBntuB7EoXA2Z42dN-XO8eokvWH8Ny9PkuUPsY

The Black Mages' version of the Opera.

Check this one out, seriously, it's amazing, there's vocal narration, and while you're running towards Ultros near the end? Lets just say it's obvious the show is continuing below you.

**Comment by edale2** [comment]
Yeqa, just listened the the entire OCR remix of the opera... I stand by my previous statement of not touching it with a 10-foot pole, as far as inclusion with the game goes.

Not only is there more vocals than instruments, they're talking about that just plain old doesn't happen in the Opera. It's probably the truest remix on the entire album, given that almost nothing of the original remains, and what does isn't recognizable anymore.

**Comment by edale2** [comment]
And with the final decision to not do the OCR version, that makes all the professionally done versions of the opera that I'm aware of completed.

I'm probably going to go over the Game Music Concert 4 version (current OTH version) one more time to see if anything outside of the Aria needs touching up, but not today.

**Comment by edale2** [comment]
I really need to find another version or two of Grand Finale, since that wasn't included in any of the Opera tracks... Not many have done remasters for it..

**Comment by Dizzy611** [comment]
Putting these in is being put off until a future version of the installer as it'll require another installer page to accomodate them. The current page is as full as it's going to get now.

**Comment by edale2** [comment]
There's 1 more professional rendition of the Opera, the Distant World's English version.

I've been very lazy in getting around to converting it since I found out about it (Final Fantasy Brave Exvius has been eating away all my free time recently)... But I will get it done.

**Comment by edale2** [comment]
https://mega.nz/#!nYREHQTL!FuvrBjtOhUOChpa8KeAonCukCRtYG9NZzNu0uDPBsIE

More Friends Album Opera, updated.

**Comment by edale2** [comment]
https://mega.nz/#!CUR2iLRb!X2H5KQVbq6_dqGmE6KveKvf_UGNfVVRYAUYezdjjRw0

Distant Worlds Opera, a second English version. ;)

**Comment by Dizzy611** [comment]
Design for the new page is finally pretty much finalized, not yet hooked up to any code but the UI stuff is there, as of commit 09819a61d3f28ff9e06d41505a0e2b30a4fe9985. @edale2, I'm testing out the "preview button" idea on the Opera stuff. Could you get me a 3-5 second representative sample (probably of the aria?) for each opera selection, as an MP3 or OGG file?

**Comment by Dizzy611** [comment]
Removing postponed tag as this is pretty much the focus of my active work atm.

**Comment by Dizzy611** [comment]
At this point my next step is to actually hook the selections in the installer up to download requests for the downloader, which also means deciding the names/folders these tracks will use on the server and uploading them for testing.

I can't really do any more high-bandwidth stuff until our bandwidth ticks over on the 29th, so I'm likely going to be fixing other, easier to test bugs until then.

**Comment by Dizzy611** [comment]
Alright, the downloader bit should now be functional. I say *should*, because I don't currently have the private key available for the main download server so I haven't synced things across yet. Therefore, I can't really test this atm. Will do so once I get the chance.

I essentially created a list of "hidden" sources just for the opera, that begin with "x" in the XML file and aren't shown on the track selection table, but are used internally.

**Comment by Dizzy611** [comment]
I've now confirmed it works (changed my mirrors around slightly for testing).

**Comment by edale2** [comment]
https://mega.nz/#F!GVwgkSxD!_gnYTjnsHEr5oFS0eNh95g
MP3 samples of each of the 5 versions of the Opera.

Closer to 40 seconds each, but under 1MB each, so works out for not increasing the size of things too much.

40ish seconds because I included a small chunk of several songs, all of them using the same chunks of the same parts, so a proper comparison can be made.

Opening fanfare -> Maria: "Oh my hero, my beloved; shall we still be made to part" -> Draco: "Oh Mariaaaaaaa" -> Ralse: "Insolent rogue, nave of the western horde!" -> Chunk of music that plays while you're chasing down Ultros in the rafters.

**Comment by Dizzy611** [comment]
Awesome, thank you! 

In other news I've synced the main mirror to my changes for the opera stuff, so it's just the Amazon mirror to fix now.

**Comment by Dizzy611** [comment]
More testing needs to be done but this has now been added to the installer and is working, complete with previews.
