### ISSUE TITLE
OTH Opera redux

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#48]
OK, I fixed up the entire OTH Opera.

https://mega.nz/#!Xc5XxQxS!m5TTlHnsuUgwt1OeR_Sl1T2ooTrZ9lRRqxJNnefycZk

Tracks 39, 65, 66, 68, and 69 have been edited, the other tracks were untouched.

On 39 (Aria) I fixed the minor timing mismatch on the 3rd stanza, as well as some touchup work on the final segment.

Tracks 65, 66, 68, and 69 have had their timings adjusted so things happen when they're supposed to. Whether that's the vocals lining up to the text, or sound effects happening at the right time (ie. the cymbals clash when Draco is run over by the chocobos in the beginning now, as it's meant to do).

Tracks 65, 66, and 69 have been normalized to -12dB, to match the -12 track 39 was already at.
Track 68 was normalized to -15dB.

The entire OTH Opera is now timed perfectly, and no further edits should be needed.

**Comment by Dizzy611** [comment]
Thankfully song source edits that don't involve adding new tracks (or more sources to existing tracks) can at this point be easily hot swapped in server-side. This should be a very quick fix. Haven't gotten the chance to listen yet.

**Comment by edale2** [comment]
Well, I'd hate to make your job too easy, so here: #49, lol

**Comment by Dizzy611** [comment]
Updated, though see bit on the ff3-3 OST fix for why this may not show up live yet.
