### ISSUE TITLE
Final Fantasy Acoustic Rendition & ChrystalChameleon FF6 Orchestrated (New Albums)

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#49]
Introducing the one, the only, Final Fantasy Acoustic Rendition. This handy, dandy album, yours for the low, low cost of free. ;-) 

https://mega.nz/#!LVBCQaSQ!LqDng39nkOaiAItHXRukXPe_4Vnec2-IjgysTWItYI8

23 tracks including everyone's theme song, the ending (1st part), Decisive Battle, Epitaph, Forever Rachel, Awakening, The Coin Song, Kids Run Through the City, Phantom Forest, Searching for Friends (without propeller effect added), Magitek Research Facility, and Kefka.

A few notes:

- The ending is only the first part, The second part is from the OST.
- Mog's Theme was NOT included on the album, I pulled the chunk of Mog's Theme from the ending to make track 49, so track 49 might not be as accurate to the original as the rest of the tracks are.
- With the exception of Mog's Theme, for reasons noted above, every track is looped perfectly, and most tracks are in the 0:40-1:15 range.

A WAV of the ending, timed properly, with ONLY the first part is here: https://mega.nz/#!XBAV2RZJ!onr7H1PcHukkUNDDMy9dImsQXr313ovKNxlxBtQQv9M
So any copy of Part 2 of the ending can be easily added.

Note on track looping info: https://pastebin.com/6wahrwnM

**Comment by Dizzy611** [comment]
okay this may be worth making a new source... Hmm. I might have a few more columns on the selector, though I might have to lower the size of the column header font some probably

**Comment by edale2** [comment]
Yea, I stumbled onto the full album while trying to find a FLAC of the Searching For Friends track (option 5 from #44 was from this album), and the album was awesome, so I HAD to convert it.

Didn't notice Mog's Theme wasn't included until I started working on Balance Is Restored, and decided to rip Mog's Theme from the ending because I got really hyped on the idea that the ending bits would match the character's themes you had actually heard the whole game (since IIRC the OST was the only version of the ending we have... because I don't count the OCR one because it's 5 minutes short of the needed time, so it partially loops... So if you used different versions of the character themes...)

**Comment by edale2** [comment]
On a slightly related (to new tracks) note... Is it possible in this mod to set it up so 2 areas that normally share the same music can use different music instead?

I ask because I stumbled across the FFVI Special Tracks Album, which includes several unused songs. There are 2 unused town songs in the album, and I was thinking it'd be cool to sneak them into the game, but without removing the existing town themes.

https://www.youtube.com/watch?v=sthdrFFZBOk
https://www.youtube.com/watch?v=0S0J5JilEOk

I was thinking Use Town 3 for South Figaro... AFTER you free it from the Empire through a good enough performance at the feast.

And I was thinking Town 2 for the town on the Veldt (I'm running there real quick right now to check the town's name and what song plays there). 

Both only in WoB.

*edit- The town on the Veldt is Mobliz, and the song is Kids Running Through the City.
And it's Kids Running Through the City in South Figaro after it's freed as well.

**Comment by Dizzy611** [comment]
Easiest way would probably be using one of those zone editors to actually change what track the zone calls for.

**Comment by edale2** [comment]
Hmmm... Looking through Zone Doctor CE, I did find how to change the music (and actually has options for a lot of unassigned tracks, so it should be easy actually adding the new tracks in), but only for the map as a whole it seems.

South Figaro has some type of event (only event on the entire map actually), that's actually in the yard of the rich man's house of all places, that seems to check some flags and plays "Under Martial Law" if they're set right, but understanding those is beyond me. Especially how it triggers when you're nowhere near the event tile...

Makes me think having Town 3 where I was thinking might not work with that program, but Town 2 for 
WoB Mobliz should work...

**Comment by edale2** [comment]
Zone Doctor CE... I an't figure it out. ONCE I was able to change the track for South Figaro to Town 3 (loading up the PCM which I assigned to track 91), but I haven't been able to reproduce that, Zone Doctor just does not want to actually save the changes to the called track...

**Comment by Dizzy611** [comment]
Event scripts are what you would use for certain areas within a map

**Comment by edale2** [comment]
Hmmm... I just stumbled across this orchestrated remaster for FFVI music; https://www.youtube.com/watch?v=t_BxsLMvj7o&list=PLdYEU9SXADalemHUSvDg52eVpDalwzkBD

It's only 27 tracks long, but it has several tracks that are only covered by OST and OCR right now, and it's a pretty good remaster to boot.

Tracks of note;
Another World of Beasts (Esper World, ff3-33)
The Fanatics (ff3-77)
Rest in Peace (ff3-62)
Epitaph (ff3-17)
Dark World (ff3-79)
Umaro (ff3-48)
Strago's Theme (ff3-8)
What? (ff3-43)
The Fierce Battle (ff3-51)
The Coin Song (ff3-11)
Forever Rachel(ff3-14)
Slam Shuffle (ff3-41)
The Day After (ff3-52)
Kefka's Tower (ff3-78)
The Magic House (ff3-55)

That's 15 tracks not covered by FFT. SSC, or OTH (though I think 4 of them are covered by the Acoustic Rendition, that's still a non OST/OCR choice for 11 tracks).

Could you take a quick listen to some of the tracks and tell me if you think I should convert them to PCM? I think they're good enough myself. but you'll be the one needing to code it into the installer...

**Comment by Dizzy611** [comment]
Going to give a quick listen to FFAR and if I like it I'm going to stuff it onto the ff6data dir in preparation for adding to the installer. Haven't given any listen to the other one yet.

**Comment by edale2** [comment]
Main draw I see with the CrystalChameleon one is that it gives a 3rd option to a lot of tracks that didn't have that before.

Oh, and Edgar & Sabin's Theme? BURSTING with that "regal" sound that you comment on in your track selection notes. Excelect instrument selection on the composer's part.

**Comment by Dizzy611** [comment]
I like the ChrystalChameleon version of "What?" a lot.

**Comment by edale2** [comment]
I left a message asking for permission to use their stuff on one of their youtube videos, but it looks like they've completely disappeared off the net about a year ago.

i'll give it a few days for a response before just going ahead and converting them, since they have the MP3s available as free downloads, and there's no actual album involved, it should be fine.

**Comment by edale2** [comment]
And ChrystalChameleon came out of digital obscurity to actually reply, and gave her (you know, I'm just gonna go with "her", annoying keeping it gender neutral, lol) full permission to convert and use her remasters.

No FLAC, the original source and project files were on a HDD that died, but I got some pretty clean MP3 copies of everything.

**Comment by edale2** [comment]
https://mega.nz/#!7UoVgRrS!ToBB8GyWtjX2J86QNdEJ8vsHzhefvj4LDPCJuR9ly5g

All 27 of ChrystalChameleon's tracks. It included the entirety of Omen, so it's actually 29 tracks.

Looping info: https://pastebin.com/FXYXymCz

**Comment by edale2** [comment]
I should mention, some of ChrystalChameleon's remasters are REALLY good. Easilly the best version of Dark World I've heard.

**Comment by Dizzy611** [comment]
So, just as an update, adding these to our sources is currently pending my finishing work on the branch I just opened, linked [here](https://github.com/Insidious611/DancingMadFF6/tree/installer-xmlification).

Essentially, I'm making it much simpler to edit the list of songs and what sources there are for each song (take a peek in the new XML file [here](https://github.com/Insidious611/DancingMadFF6/blob/installer-xmlification/installer/songs.xml)), so that I can much more easily add new sources to songs without having to rely on remembering what column of what row is what source of what song, etc :P

Once I've finished making the reader for this new XML file, I'll incorporate it into the installer (this will require a fairly major rewrite of a large chunk of the "custom track selection" page's python module, but it shouldn't be too difficult regardless), and then I can start adding new sources with a lot less silliness involved, at which point I will likely add these two new sources, then re-listen to everything to come up with an updated "sid selection" and release a new installer with the new sources and recommendations.

**Comment by Dizzy611** [comment]
Have now edited the new XML file to point to FFAR. As far as presets it was actually my most complex so far because of how many random tracks are missing, and in no relation to their placement on the OST disk layout :p. Still need to do the same for the ChrystalChameleon tracks and change the installer to actually use the new XML reader, but we're very close to having an installer that can handle these new packs.

**Comment by edale2** [comment]
So that bit I was trying to do with inserting Town 2 and Town 3 into the game in Mobliz and South Figaro?

Well... I've actually managed to get it to work in both towns. Then I start walking around the towns, enter s building and... Kids Run Through the City Corner plays... DOH!

So I start going through the individual room maps for the towns, and switching them over to the new tracks as well.

Works in _most_ of the buildings, some of them just won't switch.

I've managed to switch everything over in South Figaro (including WoR, because the internal building maps are used by both, so can't change just one of them and have things work), except for the Pub.

The Pub's default track is listed in Zone Doctor CE as "000 current music", and changing it to a different track doesn't seem to have any effect on what plays. I'm guessing there's something funny code-wise calling the music, because of the parts there where Shadow's theme plays.

Mobliz is worse, 1/2 the buildings I can't change the music in, ones likewise listed as "000 current music." Basically, every building that can be accessed in the WoR, I can't change the music on.

I'm probably going to have to find a different pair of towns to change the music for if I want to do this as more than a hack job.

Don't suppose you know if any/which towns are WoB only?

**Comment by edale2** [comment]
I think I just may have managed to finish the mod to re-introduce the 2 cut town themes.

Town 3 is still South Figaro, I managed to change the song in the Pub finally (although the music restarts when entering the pub).

Town 2 is now in the classroom in Narshe. This actually played the Prelude (track 01) before (and I thought it was only the end screen and the load screen that had that song.).

I need to do a crapton of testing to make sure I didn't break anything in the Pub, especially for when "Under Martial Law" is playing, and the scene with Shadow.

*edit- and Locke's scenario.

**Comment by edale2** [comment]
OK, Everything works fine for classroom, and South Figaro at every point in the game as near as I can tell, except for the pub.

Under Martial Law plays properly, and everything in Locke's scenario works. Problem is when Shadow's introduced in the pub, it's not playing Shadow's Theme, it's playing the new track...

I'm almost tempted to leave it like that, because that's not the most major loss, but I really wanna see if I can get this to work right.

**Comment by Dizzy611** [comment]
I thought you said FFAR has everyone's theme song? It's missing Setzer's. (ff3-16)

**Comment by edale2** [comment]
Hmmm.... So it is.

And Setzer's theme sounds way too different from his chunk of the ending for me to pull the same trick I did with Mog's Theme...

**Comment by edale2** [comment]
Quick question: Can a debugger be used to trace where in the ROM a change to RAM is loading from?

Basically, can I set up a debugger to monitor the RAM address that tells the game what music to play, and use it to locate exactly where in the ROM a command to play a certain track at a certain location is coming from? (still trying to figure out this South Figaro pub thing)

**Comment by Dizzy611** [comment]
Just leaving a note here that finishing this up is dependent on finishing up the XMLification of the installer (issue #56), which is in and of itself dependent atm on my finishing up the new song selection (see issue #41 and linked gist).

As such this issue can currently be considered blocked by #41.

**Comment by Dizzy611** [comment]
Still blocked, but now by #56. We're getting there.

**Comment by Dizzy611** [comment]
Everything necessary for these has been done now other than syncing the mirrors with my local copy and adding the code for selecting these new presets to the installer.

**Comment by Dizzy611** [comment]
Code has been added and main mirror has been synced. Other mirrors will be synced pending testing.

**Comment by Dizzy611** [comment]
Still need to sync my other mirrors, but otherwise, complete :)
