### ISSUE TITLE
ff3-3 OST fix

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#50]
https://mega.nz/#!qIpgBYwZ!di2FhqspnXb-3QeHafenrjaUtL_Lu7hBrW1DVOHWl4s

This fixes the issue with the OST version of Omen found by Spooniest on the Romhacking.net thread. 

Would have had this done a LOT earlier, but he had a death in the family, so took a while to get back to me (and tell me I had been working on the wrong track, I had thought he meant ff3-4, very easy to spot and fix the problem once I started working on the correct track, lol).

**Comment by edale2** [comment]
Oh, and the fix was simply cutting of about 1/2 a second at the end, doing a short fade at the end, then adjusting the tempo of the entire track by something like 0.05% to extend the timing that 1/2 second so nothing would change in the timing (since it's a non-looping track).

**Comment by Dizzy611** [comment]
Was going to upload this and the Opera fixes today but am having issues with my domain registration. Once I have that fixed these will be going up.

**Comment by Dizzy611** [comment]
Alright, DNS/domain issues are still there but fixing them is a matter of waiting and while I wait, I've logged in via IP and updated this and the opera. :)

**Comment by edale2** [comment]
Does the installer use DNS names, or the IP address?

Because sounds like the installer's gonna be broken until that's fixed.

**Comment by Dizzy611** [comment]
DNS has been fixed thankfully (as of like less than 5 minutes ago, it helps having a good friend and former boss as the person handling your domain registrations...), but yeah, the installer uses the DNS names. I should maybe add the IP as a fallback at some point to hedge against any future issues like this.
