### ISSUE TITLE
Madsiur's FFVI Music Player patch, Dancing Mad MSU Edition

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#58]
https://mega.nz/#!nRoAWRDT!JNlsxpVp5xQSIf9j-tsJTtDNvLmheW9QLQb-0J1dy0I

OK, so I got ahold of Madsiur, the guy who made the Music Player mod, as well as the version of it for TWUE. I wanted to get a copy of the Music Player mod with the 'exiting the menu screen' code removed, since that was what was causing the audio glitch (both his and your code running separate scripts to resume the audio). 

I also enquired about possibly adding in the 4 songs from my mod into the player as well.

I asked that he use the code from the TWUE version as a base, so it would retain compatibility with that patch as well.

A bit of back and forth, and a LOT of testing by me, and we have this result.

There are 6 patches in here, in 2 folders.

The first folder is the basic one (for just the Dancing Mad patch), the "extra songs" folder is the version that includes the songs from my patch.
Config1 = the music player is in the config screen, where 'mono"  usually is on the stereo/mono selection.
Config 2 = the music player is in the config screen, at the very bottom of the first page.
Menu = the music player is in the main menu.

The tracks have been gone over, and reworked, so the SPC versions of Dancing Mad are gone, and it properly plays all 4 tracks of the PCM Dancing Mad, and Balance is Restored 2 has been removed, since the MSU patch doesn't use it.

All the patches are compatible with TWUE 1.97a, though one thing to note, the Menu version of the patches need to be applied **AFTER** TWUE 1.97a is applied, not before, the Config versions don't have this issue.

**Comment by edale2** [comment]
Oh and Madsiur gave his full permission for the patch to be distributed with Dancing Mad, and/or through the Dancing Mad installer, we just need to be sure to credit him in the readme.

**Comment by edale2** [comment]
Oh yea, this patch is actually MORE compatible with TWUE 1.97a than the current one included with TWUE, I found a few conflicts in testing that were fixed (the TWUE one was coded for TWUE 1.90), though I'm sure Rodimus will have the updates shortly.

Oh, and the ASM files are in there too.

**Comment by edale2** [comment]
hmm... Apparently because of an issue with the 255 hour clock mod included with in the 'bugfix' version of TWUE, a change had to be made to the code for the main menu IPS to maintain compatibility with TWUE.  

Sadly this means that there _might_ be an issue if the menu patch is applied on a rom without the 255 hour clock mod, I'm guessing it would hit at the point the clock hits 99:59 (though it worked perfectly fine in all my testing without TWUE patched at all,so it might not actually be an issue).

So that means even though the main menu version is much more aesthetically pleasing, config2 might be the better patch to include in the installer, to avoid any potential issues.

**Comment by edale2** [comment]
OK, 'Troian Horse' is supposed to be 'Troian Beauty', and is a remake of a song by the same name for FFIV.

*hangs head in shame*

I've asked Madisiur for an updated set of 'extra songs' patches, and it should be a 5 second edit for him, so I should have updated music player files tomorrow hopefully.

**Comment by edale2** [comment]
https://mega.nz/#!iZ5HySCC!6BlSleNSEm50EkOQ5_X-qlOkphgO_M8a-eDpxAMsDjY

Music Player with fixed track name.

I haven't tested this yet, I'll test it sometime tomorrow.

**Comment by Dizzy611** [comment]
Added a check box for this as well as TWUE and your cut songs restoration mod into the installer in d1f185c. No code associated yet, though this should be easy to add.

**Comment by Dizzy611** [comment]
Code has been added and this is pretty much done. Am testing atm.

**Comment by Insidious611** [comment]
Testing seems to be going okay! :) Except, after installing, one problem with the cut songs restoration mod combined with this one: The "Town 2" theme if chosen plays silence.

**Comment by Dizzy611** [comment]
Tested and working with the latest code in the installer-xmlification branch! :)

**Comment by edale2** [comment]
Looks like something is being changed in the Music Player for the new TWUE update.

Don't know what yet, but I might need to get updated patches for this to maintain compatibility with the upcoming version of TWUE.

**Comment by edale2** [comment]
No problems.

The Update was just fixing a few song titles. replacing "Terra" with "Terra's Theme" and such.

The only bit that's either a non-issue because it's consistent (character names for the themes), or already fixed (Dancing Mad track titles), is 'Another World of Beasts' is displayed as 'Another World of Beast'.

Don't feel like bugging Madsiur for an update to just add 1 letter on.
