### ISSUE TITLE
Make sure TWUE author doesn't mind us mirroring his ips.

### ISSUE THREAD

**Issue by Dizzy611** [Insidious611/DancingMadFF6#62]
Need to make sure the TWUE author doesn't mind us mirroring his IPS on http://www.somebodyelsesproblem.org/ff6data/contrib/ 

I think you said you were in contact with him, @edale2? Could you get confirmation from him?

Mirroring it (or packaging it with the installer directly) is necessary for including in the installer because RHDN doesn't allow automated downloads.

This is a blocker for releasing the latest installer hotfix publicly, as we can't actually include at the very least the music player patch until we can confirm we can include the TWUE one (because I need to make sure things are patched in the right order).

**Comment by edale2** [comment]
I'll shoot Rodimus a PM.

**Comment by edale2** [comment]
Oh, the Music Player patch will work without TWUE installed, and it's only the main menu version that need to be patched after TWUE, the config versions can be patched before.

The config2 version would be a usable default patch to use if we don't get permission. I don't really like the config1 version, there's almost no chance of finding it if you don't already know where to look.

**Comment by Dizzy611** [comment]
Fair enough. I'd *like* to make the main menu version the default though.

**Comment by edale2** [comment]
Yea, I prefer the main menu version as well.

PM sent, now it's just waiting for the response.

**Comment by RodimusPrimal** [comment]
I got your PM @edale2 
I give you guys permission, but please wait until I have finished with the next update. While this shouldn't cause any errors with your current code, I'd like the version distributed be the most up to date version.  I should have it up on RHDN by the end of the week.

**Comment by Dizzy611** [comment]
Awesome. Thanks for getting back to us so quickly. I have no problem
waiting :)

**Comment by edale2** [comment]
TWUE 2.0 has been released.
http://www.romhacking.net/hacks/1386

**Comment by Dizzy611** [comment]
Awesome. Just need to sync the IPS and your changed PCM to all mirrors, fix
the typo you caught in the readme, then package up the installer.

**Comment by Dizzy611** [comment]
Alright, all done. Thanks again to @RodimusPrimal for allowing us to distribute his excellent work.
