### ISSUE TITLE
Test installer for Hotfix One completely.

### ISSUE THREAD

**Issue by Dizzy611** [Insidious611/DancingMadFF6#66]
Testing includes, in no particular order, new developer selection, new custom options (in various combinations), AWS mirror, new custom track selections, and new source presets. In addition, x86 (32-bit) installer also needs to be thoroughly tested once made.

**Comment by Dizzy611** [comment]
Currently doing a test for Developer's Selection, all optional patches enabled.

**Comment by edale2** [comment]
I was going to check out the updates to the installer, but I can't figure out how to run it with the files from the master branch.

I have python 3.6, I just don't know how to use it.

**Comment by Dizzy611** [comment]
Pretty simple, really. Assuming you're on windows, make sure Python3.6 was installed to your PATH (it's an option in the installer), then run a command prompt (Win+R, then CMD), then in the command prompt first run `pip install pycurl python-ips pyqt5 certifi` (that installs the dependencies). Then to actually run the installer, change to the directory it's in and run `python Installer.py`.

**Comment by edale2** [comment]
easy way to get command prompt into a desired folder:
Navigate to the folder you want the command prompt in
make sure no icons are selected
hold shift, and right-click in a blank area
select "open command window here "

Easier than doing it manually.

**Comment by edale2** [comment]
Oh, and once the dependencies are installed, it looks like I can just double-click installer.py to run it.

typo:
In the readme when describing the Music Player match: "Provides a music player/"sound test" in the main menu, allowing you to testand listen to the"
need a space between 'test' & 'and'.

**Comment by edale2** [comment]
"Romhacking Community Outreach" credit, don't think I've seen that one before... I'll take it! Lol.

**Comment by Dizzy611** [comment]
Good catch on the typo.

Have decided that there's no point in testing the optional patch combinations with different presets because the two areas of code don't interact in any meaningful way. So once I'm done testing all possible combinations the optional patches with the developer's selection preset, I'll be testing the new presets and then will consider testing complete.
Completed tests:
Developer's Selection, 8/8 combinations of optional patches.

**Comment by Dizzy611** [comment]
FFAR test complete.

**Comment by Dizzy611** [comment]
CRC test complete. Tests of normal 64-bit installer are now finished.
