### ISSUE TITLE
Redo timing of track 66 (Overture part 2)

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#68]
OK, so I got ahold of Rodimus to get a copy of the TWUE 2.0 patch that has all the new opera content changes implemented, because one of the later Draco parts was completely retranslated (still used the SNES original text, now uses the updated text like the rest of the Opera). This let me go over the Opera to make sure the timing for everything still matched up.

No idea why, but Overture 2 is the only part that doesn't line up perfectly anymore (all the parts that were actually changed still line up, lol).

Gimme a few days and I'll get around to re-timing the audio for track 66, I'll have it ready before the new installer goes live.

**Comment by edale2** [comment]
OK, I have a day off of work coming, so I should be able to get the song retimed soon. Hopefully will be done by tomorrow.

**Comment by edale2** [comment]
https://mega.nz/#!DMYxEC5T!zfTwx_kh1q4wjkiAJdJW3be7eyLvRjVP2itcNo32Ey4

And done!

**Comment by Dizzy611** [comment]
Reminder to self to pull this into the music folder. Still waiting on official TWUE 2.0 release for the installer (I don't want to release two installers in rapid succession so it makes more sense to wait).

**Comment by Dizzy611** [comment]
Pulled in to the various mirrors and updated for the latest release.
