### ISSUE TITLE
Installer will not connect

### ISSUE THREAD

**Issue by chipghost84** [Insidious611/DancingMadFF6#69]
When I try to connect to download server it says it can not connect. "Error: cURL Error: could not resolve: saika.ge.de.so (DNS Server returned answer with no data)"

**Comment by Dizzy611** [comment]
Bizarre, that server is way down the mirror list and shouldn't be tried unless all other mirrors, including Amazon Web Services, are down...

**Comment by Dizzy611** [comment]
Okay, there's DNS issues going on on the two primary mirrors and there *were* permissions issues with the Amazon Web Services store. I've fixed the latter and am fixing the former as we speak. But the installer should at least function now for you, for the time being.

**Comment by Insidious611** [comment]
The DNS issues seem to have resolved themselves but I've let my provider know that we're having trouble.

**Comment by Dizzy611** [comment]
I just released a new version of the installer that removes saika.ge-de.so from the mirrors list (as that is a third party mirror that's been down for quite a while), and adds a 15 second timer to each download, enabling you to more quickly fall over to the Amazon Web Services store (which should be working now) while DNS issues are still a problem with the two other mirrors. Please let me know if you're now able to install. 

I'm awaiting response from my DNS provider to fix the primary somebodyelsesproblem.org mirrors.

**Comment by Dizzy611** [comment]
Feel free to comment/reopen if you're still having issues. I'm working with my provider to figure out the DNS problems but you should still be able to download with AWS for the time being, it just will take a 15 second timeout at the beginning of each file before it downloads.

If you want to avoid waiting for this timeout, you can extract the installer with 7zip, edit "mirrors.dat", and put https://d9z02nz0xcifk.cloudfront.net/ at the top, and http://88.99.230.22/ff6data/ right under it.

**Comment by Dizzy611** [comment]
DNS issues should now be resolved.

**Comment by chipghost84** [comment]
Works now man. Thank you so much.
