### ISSUE TITLE
Recording gameplay video 

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#70]
So I was trying to record a video of the opera in the MSU-1 mod... and I've pretty much failed, lol.

I tried recording in BSNES+ first, and this just gave me a video in a weird format that can only be played back in the emulator...

I tried recording in SNES9x, but I got 10 GB of video, split into 6 segments, at 256x224 resolution at 60fps, which is actually so large it keeps crashing all the video editing programs I try loading them all up in... Which is discouraging, considering I apparently need to get them to 720p 60fps to post on youtube without losing audio quality...

What did you do to record those twitch videos you made?

**Comment by Dizzy611** [comment]
I used Open Broadcaster Software (https://obsproject.com) and I captured
the game as a window (game capture mode didn't work due to BSNES using a
weird video mode). That let me record straight into x264 and obviously also
stream straight to twitch at the same time.

For stuff I want to edit though I prefer lossless capture, in which case I
use FRAPS.

**Comment by edale2** [comment]
I'll try them out.

I was planning on going over all the different versions of the Opera I've done, making sure the timing still lines up with everything, and recording a video of each different versions.

I won't lie, with all the different versions, I'll probably end up uploading over an hour's worth of video onto youtube... onto an non-monetized account, because I'm not a youtuber, lol. (funnily enough at least one vid I posted DID get monetized... by CBS, lol. At least they didn't take it down, heh. Just a clip from Star Trek DS9).

**Comment by Dizzy611** [comment]
My previous account (where a lot of the alpha and early beta footage is)
was monetized but I lost that when YouTube changed their policies recently.

**Comment by edale2** [comment]
I've only ever posted short vids I made for forum posts, or short clips when I wanted to use a seres/movie quote in a forum post, and couldn't find the relevant clip already posted, lol.

Hell, one vid is just me saying "G'day mate, how you going?" in a very thick Australian accent, just to prove to someone on spacebattles that I could (I've always been good with accents), lol.

**Comment by edale2** [comment]
Eh, probably going to be a while before I get around to doing this now. Got the last package I've been waiting for of stuff I've ordered with my tax return.

My PC's now upgraded to 32 GB DDR4 RAM (from 16 GB), has a 256 GB  NVMe SSD (added to my roughly 7 TB of HDDs, internal and external), along with a 3d printed part holding a 40x40mm fan over the SSD, and 2 optical drives (1 bluray burner, 1 DVD burner). And I got a receiver so I can use my Xbox 360 wireless controller on my PC (my PS3 controller I've been using is dying... and I never could get rumble to work on it...).

And taking up nearly the entire 256 GB SSD... my new copy of Final Fantasy XV Windows Edition (there was no way I wasn't going to hit a data bottleneck trying to use the 4k textures on an HDD, so had to get an SSD just for the game, lol), which is henceforth going to be eating up pretty much all my spare time, lol.

Still plan to do this at some point, but it's kinda low-priority.


Oh, as a side note, if you like trackball mice (and what's not to love about them!), Logitech came out with a new model of their trackball mouse, the MX-Ergo, so as a result, their old model, the M570, has taken a MASSIVE price drop. You can pick one up for around $25 right now ($23.99 from newegg was the best price I found, then I went to a BestBuy, and got one with their price-match policy so I wouldn't have to pay delivery, lol; they were selling it for $27.99). Considering I happily paid $50 each for both of my previous ones (the M570's been around for a LONG time), this is a GREAT price.

As another side note, the fact that I got the $5 2-year replacement protection policy on it had absolutely nothing to do with the fact that I have a broken one I can easily slip in the box with the receipt to exchange for a SECOND trackball mouse. *whistles innocently*

**Comment by edale2** [comment]
https://youtu.be/4xo5oQWjXP8

Game Music Concert 4's version (OTH)

**Comment by edale2** [comment]
OBS Studio ftw.... after a LOT of trial and error getting the settings right and making sure it used the right audio codec.

**Comment by edale2** [comment]
https://youtu.be/pqk7bKMCPj8

The Black Mages' version.

**Comment by edale2** [comment]
Doing some touch-up work on the More Friends version of the opera before recording the video for that one.

**Comment by edale2** [comment]
https://youtu.be/aM407Oxzsew

More Friends album version. see #46 for updated PCMs.

**Comment by edale2** [comment]
https://youtu.be/TCyd8STWwtE

OST version... For completeness... God knows there's no other reason to use it. lol.

**Comment by edale2** [comment]
https://youtu.be/dIn5t4TGv3w

Distant Worlds version of the Opera (English):

**Comment by Dizzy611** [comment]
Closing this for now to clean up the open bugs list since this project seems to have stalled since 2018. Feel free to reopen later.
