### ISSUE TITLE
Installer giving a false positive in Avast Antivirus

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#72]
As reported by F-Bomb on Quimm:
http://forums.qhimm.com/index.php?topic=16077.msg256186#msg256186
http://forums.qhimm.com/index.php?topic=16077.msg256337#msg256337

**Comment by Dizzy611** [comment]
Contacted Avast and uploaded both executables as potential false positives, labeled as "game modification installers" and marked as my own open source work, with my email. Hopefully if they have questions they'll email me.

**Comment by Dizzy611** [comment]
Avast confirmed it was indeed a false positive, apologized, and said it'd be cleared in their definitions within 24-48 hours. Closing.
