### ISSUE TITLE
SSC Disk 2

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#75]
https://mega.nz/#!SVYyyCxR!9nb0okEsbo3N0-e-zSd2ynjqs-FcBfFs1yaCkIVhpyQ

Made from soundcloud rips, if FLAC copies are found, I'll redo them with those.

**Comment by Dizzy611** [comment]
Alright, will add to the installer for Hotfix Three when I get time. I doubt you'll find FLAC versions because I think he only really had them up on SoundCloud, as he'd originally been intending to finish the album before releasing it for sale, and just never did.

Thanks again for your work :)

**Comment by Dizzy611** [comment]
Going to try to get this uploaded to the mirrors today (no reason not to, the installer looks for specific filenames)

**Comment by Dizzy611** [comment]
Files uploaded, new sources added to songs.xml in the installer-hotfix-three branch, should be picked up automatically.
