### ISSUE TITLE
doesn't work on the odroid or vita.

### ISSUE THREAD

**Issue by NeonLightning** [Insidious611/DancingMadFF6#91]
for some reason with any libretro core on the odroid(both the one that supports msu and the ones that don't) it plays fine until you get to the first fight. then it just sits at a black screen with the music playing instead of loading the battle. only happens on the odroid not the raspberry pi.

**Comment by NeonLightning** [comment]
i tried some save states to get past there and nope its any battle.

**Comment by NeonLightning** [comment]
same issue running the latest nightly of vita retroarch

**Comment by NeonLightning** [comment]
was an issue with 1.1 instead of 1.0

**Comment by Dizzy611** [comment]
Opening a new bug with crash at battle in FF3 US V1.1. This has been reported twice now (once privately), so this is definitely reproduced.
