### ISSUE TITLE
Crash in battle on FF3 US V1.1 ROM

### ISSUE THREAD

**Issue by Dizzy611** [Insidious611/DancingMadFF6#92]
See #91 

US V1.1 ROMs appear to have a crash/freeze when you enter a battle. Otherwise, MSU-1 code working.

**Comment by Dizzy611** [comment]
Some have suggested this has to do with the sketch bug fix, but I'm unsure how.

**Comment by RoberMC** [comment]
I also have this problem, in the first battle of the game. using US 1.1 ROM. The battle music starts playing and the game freeze with a black screen.

This problem only ocurrs when applying the optional Ted Wolsey Uncensored edition 2.01 in the installer. If i do not apply it, the game works correctly, even if i apply the other two music optional patches.

EDIT: I tested with the Japanese rom, and if i apply the Ted Wolsey's optional patch, the game freezes at the middle of the intro just before the tree Mechs approach to the ledge to talk.

**Comment by edale2** [comment]
The Ted Woolsey patch will only work on a 1.0 ROM. It will not work on a 1.1 or JP ROM.

**Comment by RoberMC** [comment]
> The Ted Woolsey patch will only work on a 1.0 ROM. It will not work on a 1.1 or JP ROM.

Oh, thanks!, my fault then.

**Comment by Dizzy611** [comment]
Yeah, this has now been confirmed to have been an issue in all known cases of someone applying TWUE to the ROM. Closing this issue as fixed as the latest installer does not let you do this.
