### ISSUE TITLE
linux installer cURL error on Opera sound file download

### ISSUE THREAD

**Issue by popon0n** [Insidious611/DancingMadFF6#96]
I believe there is a dead link error or incorrect local link error for inserting the opera sound files

**Comment by popon0n** [comment]
confirmed by multiple cURL errors all around the point of opera soundfile download, and then the installer working correctly when the opera soundfile download was set to no download/SPC

**Comment by popon0n** [comment]
(when installing for SD2SNES)

**Comment by Dizzy611** [comment]
I don't currently have the ability to test the installer in Linux, but I'm trying it out on Windows to make sure it's not a dead link of some sort.

Would be helpful if you could list the exact cURL errors received.

**Comment by Dizzy611** [comment]
Closing this for now for lack of information. Please reopen if you're still having this issue and have a log of the exact cURL errors received. Install log should be in your homedir.
