### ISSUE TITLE
Can I Get mp3 Files of the Music?

### ISSUE THREAD

**Issue by Supremeoverlord3** [Insidious611/DancingMadFF6#98]
Hello, is it possible to get mp3 files of the music?

**Comment by edale2** [comment]
If you say which set of music you're looking for, I can link you to the source easily enough.
Most of them are on youtube, and it's easy to rip mp3 audio from a youtube video.

**Comment by Supremeoverlord3** [comment]
Final Fantasy IV, V, and VI. There are many files that I would be glad to get.

**Comment by edale2** [comment]
If you're just looking for Final Fantasy music in general, and not a specific track/album...
https://s3.frozen-layer.net/descargas/102379-bso-final-fantasy-music-collection-flac.torrent
Here you go, 150 GB of Final Fantasy music. It's FLAC, not MP3 though.

**Comment by Supremeoverlord3** [comment]
I was looking for the files from the improvement patch.

**Comment by edale2** [comment]
Sean Schafianski:
https://seanschafianski.bandcamp.com/album/video-game-music-remastered-final-fantasy-vi-vol-1
Looks like Sean Schafianski's partially completed Disk 2 isn't up on soundcloud anymore, so can't link to it.

OCRemix Balance and Ruin:
https://ff6.ocremix.org/

FinalFanTim:
http://forums.qhimm.com/index.php?topic=8160.0

ChrystalChameleon:
https://www.youtube.com/watch?v=t_BxsLMvj7o&list=PLdYEU9SXADalemHUSvDg52eVpDalwzkBD

The Black Mages:
All 3 of their albums are included in the torrent I linked to.

Eiko Nichols:
https://ayco.bandcamp.com/album/final-fantasy-vi-acoustic-rendition

**Comment by Supremeoverlord3** [comment]
Thank you.  FinalFanTim’s music isn’t up.

Sent from Mail for Windows 10

**Comment by edale2** [comment]
FinalFanTim:
https://www.mediafire.com/?iollgdatn5453d7
I just went through the thread checking the links for the FFVI remaster until I found one that worked.

**Comment by Supremeoverlord3** [comment]
By the way; these files don't seem to work on any of the media players that I have; what media players precisely can play them?

**Comment by edale2** [comment]
> By the way; these files don't seem to work on any of the media players that I have; what media players precisely can play them?

Which files? If you mean the PCM's for the mod, then those are specially formatted for MSU-1 playback.
https://www.zeldix.net/t1334-msu-1-pcm-plugin-for-foobar2000
That thread has a plugin for foobar that will allow it to playback MSU-1 formatted PCMs. They'll even loop seamlessly like they do in-game, assuming looping track.

**Comment by Supremeoverlord3** [comment]
Say, that's swell! Thanks.

**Comment by Supremeoverlord3** [comment]
That one doesn't seem to work.

**Comment by Dizzy611** [comment]
Closing this. Worth noting, as a final thing, that the foobar2000 plugin edale2 mentioned is how I've done most of my testing since shortly after the project began. When it began, the plugin didn't exist yet, so I did all my music testing using a very simple MSU-player SNES ROM I coded myself based on a tutorial.

**Comment by Supremeoverlord3** [comment]
Thank you.
