### ISSUE TITLE
Black Skills, Equip, and Relic screen issue with Ted Woolsey version with bugfixes and new Opera

### ISSUE THREAD

**Issue by gary-desroches** [Insidious611/DancingMadFF6#99]
I used the installer.  I selected "SD2SNES/Snes9x-msu," "Developers Recommendation," and Woolsey's patch.  I am running it on SD2SNES with the latest firmware (1.10.3).  

When I am on the overworld after leaving Narshe, the Skills, Equip, and Relic screens are messed up.  The background is black, and a lot of text is missing.  In Skills, I see the text in the left hand column, but nothing else.  In Equip, I see all text except for the items I can equip from my inventory.  Upon pressing A on Equip, the stat previews are either "AAA" or other random sprites.

**Comment by edale2** [comment]
Can you try running the ROM on Snes9x, and seeing if the problem happens there as well?

We need to know if this is an SD2SNES issue, or if something went wrong in the patching process. Neither Insidious nor I own a SD2SNES, so that's one area where testing for us is hard...

**Comment by gary-desroches** [comment]
It looked fine in SNES9x, so I tested the MSU-1 only, Woolsey's patch only, original game, etc on SD2SNES.  Turns out the original ROM has the issue as well.  My SuperCIC mod's controller hooks interfere with the game, and I needed to force 60Hz mode.

Sorry, I'll test the original ROM first next time.  Thanks for your attention, and thanks for the hack!  I'm having fun so far!
